//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.FDPs = new HashSet<FDP>();
            this.EFBDSPReleases = new HashSet<EFBDSPRelease>();
        }
    
        public int Id { get; set; }
        public string PID { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CurrentLocationAirport { get; set; }
        public Nullable<int> BaseAirportId { get; set; }
        public Nullable<System.DateTime> DateInactiveBegin { get; set; }
        public Nullable<System.DateTime> DateInactiveEnd { get; set; }
        public Nullable<double> FlightSum { get; set; }
        public Nullable<int> FlightEarly { get; set; }
        public Nullable<int> FlightLate { get; set; }
        public Nullable<bool> InActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDP> FDPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFBDSPRelease> EFBDSPReleases { get; set; }
    }
}
