//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiLog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppa_pgsEntities : DbContext
    {
        public ppa_pgsEntities()
            : base("name=ppa_pgsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ViewFlightsGantt> ViewFlightsGantts { get; set; }
        public virtual DbSet<ViewFlightsGanttNew> ViewFlightsGanttNews { get; set; }
    }
}
