//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_view_trncard
    {
        public int profile_id { get; set; }
        public string name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public int person_id { get; set; }
        public string nid { get; set; }
        public string jobgroup { get; set; }
        public string imageurl { get; set; }
        public string jobgroup_root { get; set; }
        public string clmn_caption { get; set; }
        public string clmn_name { get; set; }
        public string title { get; set; }
        public string column_name { get; set; }
        public string trncard_title { get; set; }
        public string IssueField { get; set; }
        public string ExpireField { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> interval_month { get; set; }
        public Nullable<int> Remain { get; set; }
        public string Status { get; set; }
        public int StatusId { get; set; }
    }
}
