//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string CertificateType { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public int PersonId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateIssueOld { get; set; }
        public Nullable<System.DateTime> DateExpireOld { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
