//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSessionFDPItem
    {
        public int csf_id { get; set; }
        public string session_key { get; set; }
    
        public virtual CourseSessionFDP CourseSessionFDP { get; set; }
    }
}
