//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDocument
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Remark { get; set; }
        public string FileUrl { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
