//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_type_subject
    {
        public int id { get; set; }
        public int parent_id { get; set; }
        public int course_type_id { get; set; }
        public Nullable<int> duration { get; set; }
    
        public virtual CourseType CourseType { get; set; }
    }
}
