//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frms_checklist_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public frms_checklist_category()
        {
            this.frms_checklist_category1 = new HashSet<frms_checklist_category>();
            this.frms_checklist_item = new HashSet<frms_checklist_item>();
        }
    
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int form_type_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public int sort_order { get; set; }
        public System.DateTime created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frms_checklist_category> frms_checklist_category1 { get; set; }
        public virtual frms_checklist_category frms_checklist_category2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frms_checklist_item> frms_checklist_item { get; set; }
    }
}
