//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frms_cabin_line_check
    {
        public int id { get; set; }
        public Nullable<int> instructor_id { get; set; }
        public Nullable<int> crew_id { get; set; }
        public Nullable<int> flight_id { get; set; }
        public string experience { get; set; }
        public Nullable<int> final_score { get; set; }
        public Nullable<int> line_evaluator_id { get; set; }
        public string line_evaluator { get; set; }
        public Nullable<System.DateTime> line_evaluator_sign_date { get; set; }
        public Nullable<System.DateTime> instructor_sign_date { get; set; }
        public Nullable<System.DateTime> crew_sign_date { get; set; }
        public string crew_remark { get; set; }
        public string instructor_remark { get; set; }
        public Nullable<int> on_grnd_emergency { get; set; }
        public Nullable<int> evacuation_not_required { get; set; }
        public Nullable<int> inflight_emergency { get; set; }
        public Nullable<int> brace_emergency_landing { get; set; }
        public Nullable<int> emergency_evacuation_command { get; set; }
        public Nullable<int> emergencies_takeoff_landing { get; set; }
        public Nullable<int> incident { get; set; }
        public Nullable<int> brace_impact { get; set; }
        public Nullable<int> emergency_descent { get; set; }
        public Nullable<int> flight_crew_incapacitation { get; set; }
        public Nullable<int> unlawful { get; set; }
        public Nullable<int> turbulence { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
