//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRPGroupsCourseTypeExpiring
    {
        public string JobGroupMain { get; set; }
        public string JobGroupMainCode { get; set; }
        public string JobGroupCode2 { get; set; }
        public string JobGroup { get; set; }
        public int JobGroupId { get; set; }
        public string Title { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> EmployeesCount { get; set; }
        public Nullable<int> ValidCount { get; set; }
        public Nullable<int> ExpiredCount { get; set; }
        public Nullable<int> ExpiringCount { get; set; }
        public Nullable<int> UnknownCount { get; set; }
    }
}
