//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_crm_assessment_questions_value
    {
        public int id { get; set; }
        public Nullable<int> crm_assessment_question_id { get; set; }
        public Nullable<int> answer { get; set; }
        public string comments { get; set; }
        public Nullable<int> crm_assessment_id { get; set; }
    
        public virtual trn_crm_assessment trn_crm_assessment { get; set; }
        public virtual trn_crm_assessment_questions trn_crm_assessment_questions { get; set; }
    }
}
