//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_exam_question_template
    {
        public int id { get; set; }
        public int exam_id { get; set; }
        public Nullable<int> question_category_id { get; set; }
        public Nullable<int> hardness { get; set; }
        public Nullable<int> total { get; set; }
        public string reamrk { get; set; }
    
        public virtual trn_exam trn_exam { get; set; }
    }
}
