//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_zftt_actions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trn_zftt_actions()
        {
            this.trn_zftt_action_values = new HashSet<trn_zftt_action_values>();
        }
    
        public int id { get; set; }
        public Nullable<int> section_id { get; set; }
        public string description { get; set; }
        public string assessment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_zftt_action_values> trn_zftt_action_values { get; set; }
        public virtual trn_zftt_sections trn_zftt_sections { get; set; }
    }
}
