//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnDbAppFieldMapping
    {
        public int Id { get; set; }
        public string Operator { get; set; }
        public string DbFieldIssue { get; set; }
        public string DbFieldExpire { get; set; }
        public Nullable<int> CertificateTypeId { get; set; }
        public string GroupTitle { get; set; }
        public string GroupCode { get; set; }
        public string DbFieldRemark { get; set; }
        public Nullable<int> IntervalMonth { get; set; }
        public string Identifier { get; set; }
        public string Remark { get; set; }
    }
}
