//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trm_exam_student_answer
    {
        public int id { get; set; }
        public int person_id { get; set; }
        public int question_id { get; set; }
        public int main_question_id { get; set; }
        public int answer_id { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
    }
}
