//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trn_fstd_monitoring
    {
        public int form_id { get; set; }
        public string name { get; set; }
        public int system_id { get; set; }
        public string differences { get; set; }
        public string syllabus_ref { get; set; }
        public Nullable<int> compliance_level { get; set; }
        public Nullable<bool> fchar { get; set; }
        public Nullable<bool> proc { get; set; }
    }
}
