//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trn_exam_summary
    {
        public int exam_id { get; set; }
        public int person_id { get; set; }
        public int course_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<int> passed_minutes { get; set; }
        public Nullable<int> remained_minutes { get; set; }
        public Nullable<int> total_questions { get; set; }
        public Nullable<int> total_answered { get; set; }
        public Nullable<int> total_remained { get; set; }
        public Nullable<int> score { get; set; }
        public string result { get; set; }
        public Nullable<int> result_id { get; set; }
        public Nullable<int> main_exam_id { get; set; }
    }
}
