//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trn_course_type_group
    {
        public int course_type_id { get; set; }
        public int group_id { get; set; }
        public string group_code { get; set; }
        public string group_title { get; set; }
        public string title { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<int> duration { get; set; }
        public string issue_field { get; set; }
        public string expire_field { get; set; }
        public Nullable<System.DateTime> issue_value { get; set; }
        public Nullable<System.DateTime> expire_value { get; set; }
        public Nullable<bool> show_in_profile { get; set; }
        public Nullable<bool> show_in_list { get; set; }
        public Nullable<bool> is_monitoring_enabled { get; set; }
        public string abbreviation { get; set; }
        public string remark { get; set; }
        public Nullable<bool> has_reccurent { get; set; }
        public Nullable<bool> ctg_mandatory { get; set; }
        public Nullable<bool> ctg_no_reccurent { get; set; }
        public Nullable<int> ctg_interval { get; set; }
        public Nullable<int> ctg_duration { get; set; }
        public string group_root { get; set; }
    }
}
