//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_person_folder_p1
    {
        public int id { get; set; }
        public string nid { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string file_extension { get; set; }
        public string file_name { get; set; }
        public string file_full_name { get; set; }
        public string directory { get; set; }
        public string folder { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public string part { get; set; }
    }
}
