//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_coursetype_profile
    {
        public int course_type_id { get; set; }
        public string profile_group { get; set; }
        public Nullable<bool> show_in_profile { get; set; }
        public Nullable<bool> show_in_list { get; set; }
        public string course_type { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<int> duration_initial { get; set; }
        public string issue_field { get; set; }
        public string expire_field { get; set; }
        public string remaining_field { get; set; }
        public string abbreviation { get; set; }
    }
}
