//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trn_grt
    {
        public int item_id { get; set; }
        public string item_title { get; set; }
        public string item_number { get; set; }
        public Nullable<int> item_value_id { get; set; }
        public Nullable<int> item_grade { get; set; }
        public int form_id { get; set; }
    }
}
