//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketTRN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trn_person_exam
    {
        public int id { get; set; }
        public int exam_id { get; set; }
        public Nullable<int> main_exam_id { get; set; }
        public int course_id { get; set; }
        public Nullable<int> person_id { get; set; }
        public int course_type_id { get; set; }
        public string course_type { get; set; }
        public System.DateTime course_date_start { get; set; }
        public Nullable<System.DateTime> course_date_end { get; set; }
        public string instructor { get; set; }
        public string location { get; set; }
        public Nullable<int> course_status_id { get; set; }
        public string course_status { get; set; }
        public string training_director { get; set; }
        public string course_title { get; set; }
        public string course_no { get; set; }
        public string nid { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string id_no { get; set; }
        public string instructor1 { get; set; }
        public string instructor2 { get; set; }
        public Nullable<int> instructor2_id { get; set; }
        public Nullable<int> instructor1_id { get; set; }
        public string course_sms_status { get; set; }
        public Nullable<System.DateTime> course_sms_date { get; set; }
        public Nullable<long> course_sms_refid { get; set; }
        public string course_sms_msg { get; set; }
        public Nullable<System.DateTime> exam_date_scheduled { get; set; }
        public string exam_location { get; set; }
        public string exam_address { get; set; }
        public string exam_phone { get; set; }
        public string exam_remark { get; set; }
        public Nullable<int> exam_status_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string exam_status { get; set; }
        public Nullable<decimal> exam_score { get; set; }
        public Nullable<int> exam_result_id { get; set; }
        public string exam_result { get; set; }
        public Nullable<int> exam_type_id { get; set; }
        public Nullable<int> exam_duration { get; set; }
        public Nullable<System.DateTime> exam_date_actual { get; set; }
        public Nullable<int> total_question { get; set; }
        public Nullable<int> total_answered { get; set; }
        public Nullable<int> total_correct_answer { get; set; }
        public Nullable<int> total_wrong_answer { get; set; }
        public Nullable<int> total_negative_score { get; set; }
        public Nullable<System.DateTime> person_sign_date { get; set; }
    }
}
