//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ava_course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ava_course()
        {
            this.ava_session = new HashSet<ava_session>();
            this.ava_student = new HashSet<ava_student>();
        }
    
        public int id { get; set; }
        public string CourseTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Duration_Days { get; set; }
        public Nullable<int> Duration_Hours { get; set; }
        public string Instructor { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public Nullable<int> participants_count { get; set; }
        public Nullable<int> sessions_count { get; set; }
        public string course_key { get; set; }
        public string course_type { get; set; }
        public Nullable<int> ins1_id { get; set; }
        public Nullable<int> ins2_id { get; set; }
        public string remark { get; set; }
        public Nullable<int> temp_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ava_session> ava_session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ava_student> ava_student { get; set; }
    }
}
