//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ava_student
    {
        public int id { get; set; }
        public int course_id { get; set; }
        public string name { get; set; }
        public string name_fa { get; set; }
        public string attendance { get; set; }
        public string source_name { get; set; }
        public Nullable<int> source_person_id { get; set; }
    
        public virtual ava_course ava_course { get; set; }
    }
}
