//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fly_course_student
    {
        public int id { get; set; }
        public string key { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string row_no { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<int> course_id { get; set; }
    }
}
