//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGRH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chk_turn_around_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chk_turn_around_item()
        {
            this.chk_turn_around_item_value = new HashSet<chk_turn_around_item_value>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> order_index { get; set; }
        public string ac_model { get; set; }
        public Nullable<int> time_start { get; set; }
        public Nullable<bool> domestic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chk_turn_around_item_value> chk_turn_around_item_value { get; set; }
    }
}
