//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGRH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_grh_turn_around
    {
        public int id { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> station_id { get; set; }
        public Nullable<int> fuel_litr { get; set; }
        public string fuel_sn { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public Nullable<int> sign_user_id { get; set; }
        public Nullable<int> station_manager_user_id { get; set; }
        public Nullable<System.DateTime> station_manager_sign_date { get; set; }
        public Nullable<int> pax_male { get; set; }
        public Nullable<int> pax_female { get; set; }
        public Nullable<int> pax_adult { get; set; }
        public Nullable<int> pax_child { get; set; }
        public Nullable<int> pax_infant { get; set; }
        public Nullable<System.DateTime> offblock { get; set; }
        public Nullable<System.DateTime> takeoff { get; set; }
        public Nullable<int> delay { get; set; }
        public string delay_code { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_user_id { get; set; }
        public string flight_no { get; set; }
        public string ac_type { get; set; }
        public string ac_model { get; set; }
        public string register { get; set; }
        public Nullable<int> register_id { get; set; }
        public Nullable<System.DateTime> std { get; set; }
        public Nullable<System.DateTime> sta { get; set; }
        public Nullable<System.DateTime> std_local { get; set; }
        public Nullable<System.DateTime> sta_local { get; set; }
        public Nullable<System.DateTime> std_day_local { get; set; }
        public Nullable<System.DateTime> blockoff_station_local { get; set; }
        public Nullable<System.DateTime> blockon_station_local { get; set; }
        public Nullable<System.DateTime> landing_station_local { get; set; }
        public Nullable<System.DateTime> takeoff_station_local { get; set; }
        public string flight_status { get; set; }
        public Nullable<int> block_time { get; set; }
        public Nullable<int> flight_time { get; set; }
        public Nullable<int> flight_year { get; set; }
        public Nullable<int> flight_month { get; set; }
        public Nullable<int> flight_day { get; set; }
        public string from_icao { get; set; }
        public string to_icao { get; set; }
        public string from_iata { get; set; }
        public string to_iata { get; set; }
        public Nullable<int> from_id { get; set; }
        public Nullable<int> to_id { get; set; }
        public Nullable<int> scheduled_time { get; set; }
    }
}
