//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAtoClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppa_entities : DbContext
    {
        public ppa_entities()
            : base("name=ppa_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<trn_exam_group> trn_exam_group { get; set; }
        public virtual DbSet<trn_exam_person> trn_exam_person { get; set; }
        public virtual DbSet<trn_exam_question> trn_exam_question { get; set; }
        public virtual DbSet<view_trn_exam> view_trn_exam { get; set; }
        public virtual DbSet<trn_answers> trn_answers { get; set; }
        public virtual DbSet<view_trn_profile> view_trn_profile { get; set; }
        public virtual DbSet<view_trn_exam_question> view_trn_exam_question { get; set; }
        public virtual DbSet<view_trm_exam_student_answer> view_trm_exam_student_answer { get; set; }
        public virtual DbSet<view_trn_person_exam> view_trn_person_exam { get; set; }
        public virtual DbSet<trn_person_exam> trn_person_exam { get; set; }
        public virtual DbSet<trn_person_exam_question> trn_person_exam_question { get; set; }
        public virtual DbSet<view_trn_exam_person> view_trn_exam_person { get; set; }
        public virtual DbSet<view_trn_exam_question_person> view_trn_exam_question_person { get; set; }
        public virtual DbSet<view_trn_exam_question_person_details> view_trn_exam_question_person_details { get; set; }
        public virtual DbSet<trn_exam_student_answer> trn_exam_student_answer { get; set; }
        public virtual DbSet<trn_exam> trn_exam { get; set; }
        public virtual DbSet<view_trn_exam_summary> view_trn_exam_summary { get; set; }
        public virtual DbSet<view_trn_exam_summary_details> view_trn_exam_summary_details { get; set; }
        public virtual DbSet<view_trn_student_answer> view_trn_student_answer { get; set; }
    }
}
