//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAtoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trn_exam()
        {
            this.trn_exam_question = new HashSet<trn_exam_question>();
            this.trn_exam_group = new HashSet<trn_exam_group>();
            this.trn_exam_person = new HashSet<trn_exam_person>();
            this.trn_person_exam = new HashSet<trn_person_exam>();
        }
    
        public int id { get; set; }
        public int course_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public string exam_date_persian { get; set; }
        public string location_title { get; set; }
        public string location_address { get; set; }
        public string location_phone { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> confirmed_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> confirmed_date { get; set; }
        public Nullable<int> exam_type_id { get; set; }
        public Nullable<System.DateTime> signed_by_ins1_date { get; set; }
        public Nullable<System.DateTime> signed_by_ins2_date { get; set; }
        public Nullable<System.DateTime> signed_by_director_date { get; set; }
        public Nullable<System.DateTime> signed_by_staff_date { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end_scheduled { get; set; }
        public Nullable<System.DateTime> date_end_actual { get; set; }
        public Nullable<System.DateTime> date_start_scheduled { get; set; }
        public Nullable<bool> is_negetive_point { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_exam_question> trn_exam_question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_exam_group> trn_exam_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_exam_person> trn_exam_person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_person_exam> trn_person_exam { get; set; }
    }
}
