//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAtoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_answers
    {
        public int id { get; set; }
        public Nullable<int> quesion_id { get; set; }
        public string english_title { get; set; }
        public string persian_title { get; set; }
        public Nullable<int> is_answer { get; set; }
        public Nullable<bool> is_rtl { get; set; }
    }
}
