//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAtoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trn_exam_person
    {
        public int id { get; set; }
        public Nullable<int> person_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string nid { get; set; }
        public string mobile { get; set; }
        public int course_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public string exam_date_persian { get; set; }
        public string location_title { get; set; }
        public string location_address { get; set; }
        public string location_phone { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_id { get; set; }
        public string status { get; set; }
        public Nullable<int> created_by_id { get; set; }
        public string created_by { get; set; }
        public Nullable<int> confirmed_by_id { get; set; }
        public string confirmed_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> confirmed_date { get; set; }
        public Nullable<int> exam_type_id { get; set; }
        public string exam_type { get; set; }
        public Nullable<System.DateTime> signed_by_ins1_date { get; set; }
        public Nullable<System.DateTime> signed_by_ins2_date { get; set; }
        public Nullable<System.DateTime> signed_by_director_date { get; set; }
        public Nullable<System.DateTime> signed_by_staff_date { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end_scheduled { get; set; }
        public Nullable<System.DateTime> date_end_actual { get; set; }
        public Nullable<System.DateTime> date_start_scheduled { get; set; }
        public string course_type { get; set; }
        public int course_type_id { get; set; }
        public System.DateTime course_start { get; set; }
        public Nullable<System.DateTime> course_end { get; set; }
        public string instructor { get; set; }
        public string training_director { get; set; }
        public Nullable<int> course_duration { get; set; }
        public string course_title { get; set; }
        public string course_no { get; set; }
        public string instructor2 { get; set; }
        public string result { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> total_question { get; set; }
        public Nullable<int> total_answered { get; set; }
        public Nullable<int> total_correct_answer { get; set; }
        public Nullable<int> total_wrong_answer { get; set; }
        public Nullable<int> total_negative_score { get; set; }
        public Nullable<System.DateTime> person_sign_date { get; set; }
    }
}
