//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAtoClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_trn_exam_question
    {
        public int exam_id { get; set; }
        public int exam_question_id { get; set; }
        public int question_id { get; set; }
        public string english_title { get; set; }
        public Nullable<int> category_id { get; set; }
        public bool is_rtl { get; set; }
        public int hardness { get; set; }
        public string category { get; set; }
        public string correct_answer_title { get; set; }
        public int correct_answer_id { get; set; }
    }
}
