//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ViewFDPLog> ViewFDPLogs { get; set; }
        public virtual DbSet<FDPExtra> FDPExtras { get; set; }
        public virtual DbSet<ExtensionHistory> ExtensionHistories { get; set; }
        public virtual DbSet<FDPItem> FDPItems { get; set; }
        public virtual DbSet<SchFlight> SchFlights { get; set; }
        public virtual DbSet<TableDutyFDP> TableDutyFDPs { get; set; }
        public virtual DbSet<TableFlightFDP> TableFlightFDPs { get; set; }
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<FDPMaxDaily> FDPMaxDailies { get; set; }
        public virtual DbSet<Extension> Extensions { get; set; }
        public virtual DbSet<ViewCrewDutyNoReg> ViewCrewDutyNoRegs { get; set; }
        public virtual DbSet<ViewFDPItem2> ViewFDPItem2 { get; set; }
        public virtual DbSet<ViewEmployeeLight> ViewEmployeeLights { get; set; }
        public virtual DbSet<OffItem> OffItems { get; set; }
        public virtual DbSet<HelperMaxFDP> HelperMaxFDPs { get; set; }
        public virtual DbSet<XFlightCrew> XFlightCrews { get; set; }
        public virtual DbSet<FTLFlightTimeRatioMonthly> FTLFlightTimeRatioMonthlies { get; set; }
        public virtual DbSet<ViewCrewDutyTimeLineNew> ViewCrewDutyTimeLineNews { get; set; }
        public virtual DbSet<ViewCrewValidFTL> ViewCrewValidFTLs { get; set; }
        public virtual DbSet<ViewFlightCrewX> ViewFlightCrewXes { get; set; }
        public virtual DbSet<AppFTL> AppFTLs { get; set; }
        public virtual DbSet<FDP> FDPs { get; set; }
        public virtual DbSet<ViewCrewDuty> ViewCrewDuties { get; set; }
        public virtual DbSet<ViewFDPRest> ViewFDPRests { get; set; }
        public virtual DbSet<ViewCrewDutyPulsePocket> ViewCrewDutyPulsePockets { get; set; }
        public virtual DbSet<AppCrewFlight> AppCrewFlights { get; set; }
        public virtual DbSet<ViewCourseFDP> ViewCourseFDPs { get; set; }
        public virtual DbSet<recency_route> recency_route { get; set; }
        public virtual DbSet<AppFTLAb> AppFTLAbs { get; set; }
        public virtual DbSet<OFPImport> OFPImports { get; set; }
        public virtual DbSet<view_recency_route> view_recency_route { get; set; }
        public virtual DbSet<view_route_count> view_route_count { get; set; }
        public virtual DbSet<CrewPickupSM> CrewPickupSMS { get; set; }
        public virtual DbSet<view_report_duty> view_report_duty { get; set; }
    }
}
