//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_consequence_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qa_consequence_item()
        {
            this.qa_consequence = new HashSet<qa_consequence>();
            this.qa_consequence_item1 = new HashSet<qa_consequence_item>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string remark { get; set; }
        public string code { get; set; }
        public string full_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_consequence> qa_consequence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_consequence_item> qa_consequence_item1 { get; set; }
        public virtual qa_consequence_item qa_consequence_item2 { get; set; }
    }
}
