//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_corrective_action
    {
        public int id { get; set; }
        public Nullable<int> risk_id { get; set; }
        public string action { get; set; }
        public string responsible_staff { get; set; }
        public Nullable<int> responsible_staff_id { get; set; }
        public Nullable<System.DateTime> time_limit_date { get; set; }
        public string time_limit_remark { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string qa_approval { get; set; }
        public Nullable<int> qa_approval_id { get; set; }
        public Nullable<System.DateTime> qa_approval_date { get; set; }
        public string action_type { get; set; }
        public string action_category { get; set; }
    
        public virtual qa_risk_assessment qa_risk_assessment { get; set; }
    }
}
