//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_form_visited_history
    {
        public int form_type_id { get; set; }
        public int form_id { get; set; }
        public int employee_id { get; set; }
    }
}
