//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_risk_assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qa_risk_assessment()
        {
            this.qa_corrective_action = new HashSet<qa_corrective_action>();
            this.qa_monitor = new HashSet<qa_monitor>();
            this.qa_risk_attachment = new HashSet<qa_risk_attachment>();
        }
    
        public int id { get; set; }
        public string initial_probability { get; set; }
        public string initial_severity { get; set; }
        public string initial_level { get; set; }
        public string final_probability { get; set; }
        public string final_severity { get; set; }
        public string final_level { get; set; }
        public string approval_relevant_department { get; set; }
        public Nullable<int> approval_relevant_department_id { get; set; }
        public Nullable<System.DateTime> approval_relevant_department_date { get; set; }
        public string approval_qa { get; set; }
        public Nullable<int> approval_qa_id { get; set; }
        public Nullable<System.DateTime> approval_qa_date { get; set; }
        public string om_form_no { get; set; }
        public string om_form_date { get; set; }
        public string om_form_rev { get; set; }
        public string om_form_issue { get; set; }
        public string remark { get; set; }
        public string id_source { get; set; }
        public Nullable<bool> has_relevant { get; set; }
        public Nullable<int> initial_acceptability_id { get; set; }
        public Nullable<int> initital_description_id { get; set; }
        public string initial_responsible_manager { get; set; }
        public Nullable<System.DateTime> initial_responsible_sign { get; set; }
        public string initial_qa_approval { get; set; }
        public Nullable<System.DateTime> initial_qa_sign { get; set; }
        public Nullable<int> final_acceptability_id { get; set; }
        public Nullable<int> final_description_id { get; set; }
        public Nullable<System.DateTime> final_date { get; set; }
        public string res1 { get; set; }
        public string res2 { get; set; }
        public Nullable<int> hazard_id { get; set; }
        public Nullable<int> risk_id { get; set; }
        public Nullable<int> initial_value { get; set; }
        public Nullable<int> final_value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_corrective_action> qa_corrective_action { get; set; }
        public virtual qa_hazard qa_hazard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_monitor> qa_monitor { get; set; }
        public virtual qa_risks qa_risks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_risk_attachment> qa_risk_attachment { get; set; }
    }
}
