//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_risk_acceptability
    {
        public int id { get; set; }
        public Nullable<int> risk_id { get; set; }
        public string risk_type { get; set; }
        public string responsible_manager { get; set; }
        public Nullable<int> responsible_manager_id { get; set; }
        public Nullable<System.DateTime> responsible_manager_date { get; set; }
        public Nullable<System.DateTime> responsible_manager_qa_date { get; set; }
        public Nullable<int> responsible_manager_qa_id { get; set; }
        public Nullable<int> level_id { get; set; }
        public string level_remark { get; set; }
        public Nullable<int> risk_description_id { get; set; }
    }
}
