//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_root_cause_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qa_root_cause_item()
        {
            this.qa_root_cause = new HashSet<qa_root_cause>();
            this.qa_root_cause_item1 = new HashSet<qa_root_cause_item>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string code { get; set; }
        public string full_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_root_cause> qa_root_cause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_root_cause_item> qa_root_cause_item1 { get; set; }
        public virtual qa_root_cause_item qa_root_cause_item2 { get; set; }
    }
}
