//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recency_route
    {
        public int id { get; set; }
        public Nullable<int> crew_id { get; set; }
        public Nullable<int> from_id { get; set; }
        public Nullable<int> to_id { get; set; }
        public Nullable<System.DateTime> date_flight { get; set; }
        public Nullable<bool> is_allowed { get; set; }
        public Nullable<int> fdpitem_id { get; set; }
        public Nullable<System.DateTime> date_expire { get; set; }
    }
}
