//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_route_count
    {
        public string FromIATA { get; set; }
        public string ToIATA { get; set; }
        public string FromICAO { get; set; }
        public string ToICAO { get; set; }
        public Nullable<int> FltCount { get; set; }
    }
}
