//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XFlightCrew
    {
        public Nullable<int> CrewId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroup { get; set; }
        public int SexId { get; set; }
        public string Sex { get; set; }
        public int GroupOrder { get; set; }
        public int IsCockpit { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> flt_position_id { get; set; }
        public string PFirstName { get; set; }
        public string PLastName { get; set; }
        public string PName { get; set; }
        public string NID { get; set; }
        public string MainGroup { get; set; }
    }
}
