//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightDocument
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentUrl { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateVisite { get; set; }
        public string VisitedBy { get; set; }
        public string Title { get; set; }
    }
}
