//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_discretion_item
    {
        public int id { get; set; }
        public int form_id { get; set; }
        public int item_id { get; set; }
        public string remark { get; set; }
    
        public virtual form_discretion form_discretion { get; set; }
    }
}
