//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frm_onboard_status
    {
        public int id { get; set; }
        public int item_id { get; set; }
        public string status { get; set; }
        public Nullable<int> crew_id { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> date_status { get; set; }
        public Nullable<System.DateTime> date_sign { get; set; }
        public Nullable<int> flight_id { get; set; }
    
        public virtual FlightInformation FlightInformation { get; set; }
        public virtual frm_onboard_item frm_onboard_item { get; set; }
    }
}
