//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frm_onboard_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public frm_onboard_item()
        {
            this.frm_onboard_status = new HashSet<frm_onboard_status>();
        }
    
        public int id { get; set; }
        public string category { get; set; }
        public string item { get; set; }
        public Nullable<int> order_index { get; set; }
        public string remark { get; set; }
        public Nullable<int> category_index { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frm_onboard_status> frm_onboard_status { get; set; }
    }
}
