//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCrewFlight> AppCrewFlights { get; set; }
        public virtual DbSet<FDPItem> FDPItems { get; set; }
        public virtual DbSet<XAppLeg> XAppLegs { get; set; }
        public virtual DbSet<OFPImportProp> OFPImportProps { get; set; }
        public virtual DbSet<FlightDocument> FlightDocuments { get; set; }
        public virtual DbSet<FlightInformation> FlightInformations { get; set; }
        public virtual DbSet<EFBValue> EFBValues { get; set; }
        public virtual DbSet<AppLegOP> AppLegOPS { get; set; }
        public virtual DbSet<EFBDSPRelease> EFBDSPReleases { get; set; }
        public virtual DbSet<ViewEFBDSPReleas> ViewEFBDSPReleases { get; set; }
        public virtual DbSet<PersonCustomer> PersonCustomers { get; set; }
        public virtual DbSet<ViewFlightCrewNew> ViewFlightCrewNews { get; set; }
        public virtual DbSet<AppCrewFlightJL> AppCrewFlightJLs { get; set; }
        public virtual DbSet<AppFDPRest> AppFDPRests { get; set; }
        public virtual DbSet<AppLeg> AppLegs { get; set; }
        public virtual DbSet<geo_apt_sunrise> geo_apt_sunrise { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<EFBVoyageReport> EFBVoyageReports { get; set; }
        public virtual DbSet<AppLegJL> AppLegJLs { get; set; }
        public virtual DbSet<FDP> FDPs { get; set; }
        public virtual DbSet<ViewQACSREvent> ViewQACSREvents { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<EFBASR> EFBASRs { get; set; }
        public virtual DbSet<ViewEFBASR> ViewEFBASRs { get; set; }
        public virtual DbSet<EFBFlightIrregularity> EFBFlightIrregularities { get; set; }
        public virtual DbSet<EFBReason> EFBReasons { get; set; }
        public virtual DbSet<EFBDutyDisorder> EFBDutyDisorders { get; set; }
        public virtual DbSet<qa_notification_history> qa_notification_history { get; set; }
        public virtual DbSet<qa_notification_receiver> qa_notification_receiver { get; set; }
        public virtual DbSet<ViewProfile> ViewProfiles { get; set; }
        public virtual DbSet<OFPB_WindTemperature> OFPB_WindTemperature { get; set; }
        public virtual DbSet<view_discretion_form> view_discretion_form { get; set; }
        public virtual DbSet<ViewEmployee> ViewEmployees { get; set; }
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<OFPB_Prop> OFPB_Prop { get; set; }
        public virtual DbSet<ViewFDPRest> ViewFDPRests { get; set; }
        public virtual DbSet<ViewQAMaintenance> ViewQAMaintenances { get; set; }
        public virtual DbSet<form_discretion> form_discretion { get; set; }
        public virtual DbSet<OFPB_MainNavLog> OFPB_MainNavLog { get; set; }
        public virtual DbSet<OFPB_Root> OFPB_Root { get; set; }
        public virtual DbSet<view_ofbb_root_actual> view_ofbb_root_actual { get; set; }
        public virtual DbSet<view_ofpb_navlog> view_ofpb_navlog { get; set; }
        public virtual DbSet<view_ofpb_navlog_actual> view_ofpb_navlog_actual { get; set; }
        public virtual DbSet<view_ofpb_root> view_ofpb_root { get; set; }
        public virtual DbSet<view_ofpb_root_report> view_ofpb_root_report { get; set; }
        public virtual DbSet<view_ofpb_wt> view_ofpb_wt { get; set; }
        public virtual DbSet<DayGP> DayGPs { get; set; }
        public virtual DbSet<form_discretion_item> form_discretion_item { get; set; }
        public virtual DbSet<FormVacation> FormVacations { get; set; }
        public virtual DbSet<journeylog_atl> journeylog_atl { get; set; }
        public virtual DbSet<ViewLegCrew> ViewLegCrews { get; set; }
        public virtual DbSet<ViewQACSR> ViewQACSRs { get; set; }
        public virtual DbSet<XFlightCrew> XFlightCrews { get; set; }
        public virtual DbSet<discretion_form> discretion_form { get; set; }
        public virtual DbSet<ViewEFBVoyageIrr> ViewEFBVoyageIrrs { get; set; }
        public virtual DbSet<ViewEFBVoyageIrrAll> ViewEFBVoyageIrrAlls { get; set; }
        public virtual DbSet<ViewEFBVoyageReason> ViewEFBVoyageReasons { get; set; }
        public virtual DbSet<ViewEFBVoyageReasonAll> ViewEFBVoyageReasonAlls { get; set; }
        public virtual DbSet<ViewEFBVoyageReport> ViewEFBVoyageReports { get; set; }
        public virtual DbSet<ViewEFBVoyageReportsAll> ViewEFBVoyageReportsAlls { get; set; }
        public virtual DbSet<QAFollowingUp> QAFollowingUps { get; set; }
        public virtual DbSet<QAResponsibilty> QAResponsibilties { get; set; }
        public virtual DbSet<OFPImport> OFPImports { get; set; }
        public virtual DbSet<ViewEmployeeLight> ViewEmployeeLights { get; set; }
        public virtual DbSet<ViewQAGround> ViewQAGrounds { get; set; }
        public virtual DbSet<ViewQAHazard> ViewQAHazards { get; set; }
        public virtual DbSet<ViewQASecurity> ViewQASecurities { get; set; }
        public virtual DbSet<ViewQaVoyageReport> ViewQaVoyageReports { get; set; }
    }
}
