//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCrewFlight> AppCrewFlights { get; set; }
        public virtual DbSet<FDPItem> FDPItems { get; set; }
        public virtual DbSet<XAppLeg> XAppLegs { get; set; }
        public virtual DbSet<OFPImportProp> OFPImportProps { get; set; }
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<FlightDocument> FlightDocuments { get; set; }
        public virtual DbSet<FlightInformation> FlightInformations { get; set; }
        public virtual DbSet<EFBValue> EFBValues { get; set; }
        public virtual DbSet<AppLegOP> AppLegOPS { get; set; }
        public virtual DbSet<EFBDSPRelease> EFBDSPReleases { get; set; }
        public virtual DbSet<ViewEFBDSPReleas> ViewEFBDSPReleases { get; set; }
        public virtual DbSet<PersonCustomer> PersonCustomers { get; set; }
        public virtual DbSet<ViewFlightCrewNew> ViewFlightCrewNews { get; set; }
        public virtual DbSet<AppCrewFlightJL> AppCrewFlightJLs { get; set; }
        public virtual DbSet<AppFDPRest> AppFDPRests { get; set; }
        public virtual DbSet<AppLeg> AppLegs { get; set; }
        public virtual DbSet<geo_apt_sunrise> geo_apt_sunrise { get; set; }
        public virtual DbSet<OFPImport> OFPImports { get; set; }
        public virtual DbSet<ViewEFBASR> ViewEFBASRs { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<ViewEmployee> ViewEmployees { get; set; }
        public virtual DbSet<DayGP> DayGPs { get; set; }
        public virtual DbSet<ViewEFBVoyageReport> ViewEFBVoyageReports { get; set; }
        public virtual DbSet<ViewLegCrew> ViewLegCrews { get; set; }
        public virtual DbSet<EFBASR> EFBASRs { get; set; }
        public virtual DbSet<XFlightCrew> XFlightCrews { get; set; }
        public virtual DbSet<EFBVoyageReport> EFBVoyageReports { get; set; }
        public virtual DbSet<ViewFDPRest> ViewFDPRests { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<journeylog_atl> journeylog_atl { get; set; }
        public virtual DbSet<AppLegJL> AppLegJLs { get; set; }
        public virtual DbSet<FDP> FDPs { get; set; }
        public virtual DbSet<discretion_form> discretion_form { get; set; }
        public virtual DbSet<view_discretion_form> view_discretion_form { get; set; }
    }
}
