//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPB_Prop
    {
        public int Id { get; set; }
        public int OFPId { get; set; }
        public string PropName { get; set; }
        public string PropValue { get; set; }
        public string PropType { get; set; }
        public string User { get; set; }
        public string DateUpdate { get; set; }
        public Nullable<decimal> DateUpdateLocal { get; set; }
        public string Remark { get; set; }
        public string PropertyName { get; set; }
        public string TableName { get; set; }
    
        public virtual OFPB_Root OFPB_Root { get; set; }
    }
}
