//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_notification_receiver
    {
        public int id { get; set; }
        public Nullable<int> rec_id { get; set; }
        public string rec_name { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string mobile2 { get; set; }
        public string email2 { get; set; }
    }
}
