//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ofpb_wt
    {
        public int Id { get; set; }
        public string FlightLevel { get; set; }
        public string Wind { get; set; }
        public string Temperature { get; set; }
        public string WayPoint { get; set; }
        public string WindTemprature { get; set; }
        public Nullable<int> OFPId { get; set; }
        public string Type { get; set; }
    }
}
