//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_frm_onboard_item
    {
        public int id { get; set; }
        public string category { get; set; }
        public string item { get; set; }
        public Nullable<int> order_index { get; set; }
        public string remark { get; set; }
        public Nullable<int> category_index { get; set; }
        public string status { get; set; }
    }
}
