//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAPSB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ofpb_root
    {
        public int Id { get; set; }
        public string ReferenceNo { get; set; }
        public string AirlineName { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<int> CruisePerformanceFactor { get; set; }
        public Nullable<int> ContingencyPercent { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> GenerationDate { get; set; }
        public Nullable<System.DateTime> ScheduledTimeDeparture { get; set; }
        public Nullable<System.DateTime> ScheduledTimeArrival { get; set; }
        public string TailNo { get; set; }
        public string CruiseSpeed { get; set; }
        public Nullable<int> CostIndex { get; set; }
        public Nullable<int> MainFlightLevel { get; set; }
        public Nullable<int> DryOperatingWeight { get; set; }
        public Nullable<int> Payload { get; set; }
        public Nullable<int> GroundDistance { get; set; }
        public Nullable<int> AirDistance { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Alternate1 { get; set; }
        public string Alternate2 { get; set; }
        public string TakeoffAlternate { get; set; }
        public Nullable<int> MODAlernate1 { get; set; }
        public Nullable<int> MODAlternate2 { get; set; }
        public Nullable<int> Cockpit { get; set; }
        public Nullable<int> Cabin { get; set; }
        public Nullable<int> Extra { get; set; }
        public Nullable<int> Pantry { get; set; }
        public string Pilot1 { get; set; }
        public string Pilot2 { get; set; }
        public string Dispatcher { get; set; }
        public Nullable<int> OriginElevation { get; set; }
        public Nullable<int> DestinationElevation { get; set; }
        public Nullable<int> Alternate1Elevation { get; set; }
        public Nullable<int> Alternate2Elevation { get; set; }
        public Nullable<int> TakeoffAlternateElevation { get; set; }
        public string MaxShear { get; set; }
        public Nullable<int> MaximumZeroFuelWeight { get; set; }
        public Nullable<int> MaximumTakeoffWeight { get; set; }
        public Nullable<int> MaximumLandingWeight { get; set; }
        public Nullable<int> EstimatedZeroFuelWeight { get; set; }
        public Nullable<int> EstimatedTakeoffWeight { get; set; }
        public Nullable<int> EstimatedLandingWeight { get; set; }
        public string MainRoute { get; set; }
        public string Alternate1Route { get; set; }
        public string Alternate2Route { get; set; }
        public string TakeoffAlternateRoute { get; set; }
        public Nullable<System.DateTime> PlanValidity { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public Nullable<int> SignedbyId { get; set; }
        public string SignedbyLICL { get; set; }
        public Nullable<int> RawOFPId { get; set; }
        public string MaxWindShearLevel { get; set; }
        public string MaxWindShearPointName { get; set; }
        public string FlightRule { get; set; }
        public string ICAOFlightPlan { get; set; }
        public Nullable<int> fuel_trip { get; set; }
        public Nullable<int> fuel_alt1 { get; set; }
        public Nullable<int> fuel_alt2 { get; set; }
        public Nullable<int> fuel_alt { get; set; }
        public Nullable<int> fuel_holding { get; set; }
        public Nullable<decimal> fuel_contigency { get; set; }
        public Nullable<int> fuel_taxiout { get; set; }
        public Nullable<int> fuel_taxiin { get; set; }
        public Nullable<int> fuel_min_required { get; set; }
        public Nullable<int> fuel_additional { get; set; }
        public Nullable<int> fuel_extra { get; set; }
        public Nullable<int> fuel_total { get; set; }
        public Nullable<int> fuel_landing { get; set; }
        public Nullable<int> fuel_mod_alt1 { get; set; }
        public Nullable<int> fuel_mod_alt2 { get; set; }
        public Nullable<int> time_trip { get; set; }
        public Nullable<int> time_holding { get; set; }
        public Nullable<int> time_alt { get; set; }
        public Nullable<int> time_alt1 { get; set; }
        public Nullable<int> time_alt2 { get; set; }
        public Nullable<int> time_alt_takeof { get; set; }
        public Nullable<int> time_contigency { get; set; }
        public Nullable<int> time_min_required { get; set; }
        public Nullable<int> time_additional { get; set; }
        public Nullable<int> time_extra { get; set; }
        public Nullable<int> time_total { get; set; }
        public string fuel_extra_due { get; set; }
        public Nullable<int> dis_trip { get; set; }
        public Nullable<int> dis_alt1 { get; set; }
        public Nullable<int> dis_alt2 { get; set; }
        public Nullable<int> dis_alt_takeoff { get; set; }
        public Nullable<int> dis_ground { get; set; }
        public Nullable<int> dis_air { get; set; }
        public string burnoffadj_value { get; set; }
        public string burnoffadj_fuel { get; set; }
        public string heightchange_value { get; set; }
        public string heightchange_fuel { get; set; }
    }
}
