//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProfile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IdeaUnique> IdeaUniques { get; set; }
        public virtual DbSet<ViewIdeaUniqueLast> ViewIdeaUniqueLasts { get; set; }
        public virtual DbSet<ThirdPartySyncHistory> ThirdPartySyncHistories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeLocation> EmployeeLocations { get; set; }
        public virtual DbSet<PersonAircraftType> PersonAircraftTypes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ViewPersonDocumentFile> ViewPersonDocumentFiles { get; set; }
        public virtual DbSet<ViewPersonAircraftType> ViewPersonAircraftTypes { get; set; }
        public virtual DbSet<ViewEmployeeLocation> ViewEmployeeLocations { get; set; }
        public virtual DbSet<PersonCustomer> PersonCustomers { get; set; }
        public virtual DbSet<ViewEmployeeLight> ViewEmployeeLights { get; set; }
        public virtual DbSet<LoginInfo> LoginInfoes { get; set; }
        public virtual DbSet<CertificateHistory> CertificateHistories { get; set; }
        public virtual DbSet<ViewOPC> ViewOPCs { get; set; }
        public virtual DbSet<ViewCrewPickupSM> ViewCrewPickupSMS { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<ViewProfile> ViewProfiles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<PersonDocument> PersonDocuments { get; set; }
        public virtual DbSet<ViewPersonDocument> ViewPersonDocuments { get; set; }
    }
}
