//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOPC
    {
        public int Id { get; set; }
        public string NID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone2 { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> ProficiencyCheckDateOPC { get; set; }
        public Nullable<System.DateTime> ProficiencyValidUntilOPC { get; set; }
        public string FaxTelNumber { get; set; }
        public string LicenceTitle { get; set; }
        public string NDTNumber { get; set; }
    }
}
