//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leg
    {
        public System.DateTime DateUTC { get; set; }
        public string FltNo { get; set; }
        public string DepStn { get; set; }
        public string ArrStn { get; set; }
        public Nullable<System.DateTime> DepTime { get; set; }
        public Nullable<System.DateTime> ArrTime { get; set; }
        public Nullable<System.DateTime> DepTimeLCL { get; set; }
        public Nullable<System.DateTime> ArrTimeLCL { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public string STC { get; set; }
        public string ACType { get; set; }
        public string ACReg { get; set; }
        public string Flt { get; set; }
        public string UpdateFlag { get; set; }
        public string ScheduleGroup { get; set; }
        public string TurnType { get; set; }
        public string RouteType { get; set; }
        public string LegDesc { get; set; }
        public string Change { get; set; }
        public Nullable<int> Importance { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateScher { get; set; }
        public string Comment { get; set; }
        public string FltGroup { get; set; }
        public Nullable<System.DateTime> StandardTime { get; set; }
        public Nullable<bool> Holyday { get; set; }
        public string HolydayName { get; set; }
        public Nullable<System.DateTime> NormalCorrectedTime { get; set; }
        public Nullable<System.DateTime> ChangedCorrectedTime { get; set; }
    }
}
