//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class load_sheet_raw
    {
        public int id { get; set; }
        public string airline { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string content { get; set; }
        public string remark { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> signed_by_id { get; set; }
        public Nullable<System.DateTime> date_sign { get; set; }
        public string pic { get; set; }
        public string lic_no { get; set; }
    }
}
