//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPAEntities : DbContext
    {
        public PPAEntities()
            : base("name=PPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<OFPSkyPuter> OFPSkyPuters { get; set; }
        public virtual DbSet<EFBDSPRelease> EFBDSPReleases { get; set; }
        public virtual DbSet<FlightCard> FlightCards { get; set; }
        public virtual DbSet<OFPImportItem> OFPImportItems { get; set; }
        public virtual DbSet<OFPImportProp> OFPImportProps { get; set; }
        public virtual DbSet<FlightInformation> FlightInformations { get; set; }
        public virtual DbSet<ViewOFPPoint> ViewOFPPoints { get; set; }
        public virtual DbSet<OFPPoint> OFPPoints { get; set; }
        public virtual DbSet<OFPB_BurnOffAdjustment> OFPB_BurnOffAdjustment { get; set; }
        public virtual DbSet<OFPB_Distances> OFPB_Distances { get; set; }
        public virtual DbSet<OFPB_Fuels> OFPB_Fuels { get; set; }
        public virtual DbSet<OFPB_HeightChange> OFPB_HeightChange { get; set; }
        public virtual DbSet<OFPB_Times> OFPB_Times { get; set; }
        public virtual DbSet<OFPB_WindTemperature> OFPB_WindTemperature { get; set; }
        public virtual DbSet<OFPB_Root> OFPB_Root { get; set; }
        public virtual DbSet<OFPB_MainNavLog> OFPB_MainNavLog { get; set; }
        public virtual DbSet<load_sheet_raw> load_sheet_raw { get; set; }
        public virtual DbSet<OFPImport> OFPImports { get; set; }
    }
}
