//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPB_Distances
    {
        public int Id { get; set; }
        public Nullable<int> Trip { get; set; }
        public Nullable<int> Alternate1 { get; set; }
        public Nullable<int> Alternate2 { get; set; }
        public Nullable<int> RootId { get; set; }
    
        public virtual OFPB_Root OFPB_Root { get; set; }
    }
}
