//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQATemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQAComment
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string name { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateComment { get; set; }
        public string ReceiverList { get; set; }
    }
}
