//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQATemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQADashCyber
    {
        public int year { get; set; }
        public int month { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public string Register { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string route { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
