//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FR_Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FR_Flight()
        {
            this.FR_Flight_Track = new HashSet<FR_Flight_Track>();
        }
    
        public int Id { get; set; }
        public string FlightId { get; set; }
        public string FlightNo { get; set; }
        public string Register { get; set; }
        public string Model { get; set; }
        public string Airline { get; set; }
        public string AirlineIATA { get; set; }
        public string AirlineICAO { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateFlight { get; set; }
        public Nullable<int> APFlightId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FR_Flight_Track> FR_Flight_Track { get; set; }
    }
}
