//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFR_Flight
    {
        public int Id { get; set; }
        public string FlightId { get; set; }
        public string FlightNo { get; set; }
        public string Register { get; set; }
        public string Model { get; set; }
        public string Airline { get; set; }
        public string AirlineIATA { get; set; }
        public string AirlineICAO { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> APFlightId { get; set; }
        public Nullable<System.DateTime> DateFlight { get; set; }
        public string FlightStatus { get; set; }
        public int FlightStatusId { get; set; }
        public Nullable<System.DateTime> Dep { get; set; }
        public Nullable<System.DateTime> Arr { get; set; }
        public Nullable<System.DateTime> DepLocal { get; set; }
        public Nullable<System.DateTime> ArrLocal { get; set; }
    }
}
