//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFR_OFPPoint
    {
        public int OFPId { get; set; }
        public string Plan { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public int Id { get; set; }
        public string WAP { get; set; }
        public string VIA { get; set; }
        public string ALT { get; set; }
        public string WIND { get; set; }
        public string TRK { get; set; }
        public string TMP { get; set; }
        public string BODY { get; set; }
        public string FRQ { get; set; }
        public string MEA { get; set; }
        public string GMR { get; set; }
        public string DIS { get; set; }
        public string TDS { get; set; }
        public string FRE { get; set; }
        public string FUS { get; set; }
        public string TAS { get; set; }
        public string GSP { get; set; }
        public Nullable<int> TTM { get; set; }
        public Nullable<int> TME { get; set; }
        public string FlightNo { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> DateFlight { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string ETA { get; set; }
        public string ETD { get; set; }
        public string ALT1 { get; set; }
        public string ALT2 { get; set; }
        public string Register { get; set; }
    }
}
