//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftConfigurationCrew
    {
        public int Id { get; set; }
        public int ConfigId { get; set; }
        public string CrewID { get; set; }
        public string CrewType { get; set; }
        public string CrewName { get; set; }
        public string Initials { get; set; }
        public string GSM { get; set; }
        public Nullable<double> Mass { get; set; }
    
        public virtual AircraftConfiguration AircraftConfiguration { get; set; }
    }
}
