//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportFrequencies2
    {
        public int Id { get; set; }
        public int AirportId { get; set; }
        public string Value { get; set; }
        public string Information { get; set; }
    
        public virtual Airport Airport { get; set; }
    }
}
