//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportWeatherData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirportWeatherData()
        {
            this.ContingencySavingDatas = new HashSet<ContingencySavingData>();
            this.ContingencySavingDatas1 = new HashSet<ContingencySavingData>();
            this.ContingencySavingDatas2 = new HashSet<ContingencySavingData>();
        }
    
        public int Id { get; set; }
        public string ICAO { get; set; }
        public Nullable<int> TAFId { get; set; }
        public Nullable<int> MetarId { get; set; }
    
        public virtual Metar Metar { get; set; }
        public virtual Taf Taf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContingencySavingData> ContingencySavingDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContingencySavingData> ContingencySavingDatas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContingencySavingData> ContingencySavingDatas2 { get; set; }
    }
}
