//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alt1Points
    {
        public int FlightID { get; set; }
        public int ID { get; set; }
        public string IDENT { get; set; }
        public int FL { get; set; }
        public int Wind { get; set; }
        public int Vol { get; set; }
        public int ISA { get; set; }
        public int LegTime { get; set; }
        public decimal LegCourse { get; set; }
        public int LegDistance { get; set; }
        public int LegCAT { get; set; }
        public string LegName { get; set; }
        public string LegAWY { get; set; }
        public decimal FuelUsed { get; set; }
        public int FuelFlow { get; set; }
        public decimal LAT { get; set; }
        public decimal LON { get; set; }
        public int VARIATION { get; set; }
        public int ACCDIST { get; set; }
        public int ACCTIME { get; set; }
        public decimal MagCourse { get; set; }
        public int TrueAirSpeed { get; set; }
        public int GroundSpeed { get; set; }
        public decimal FuelRemaining { get; set; }
        public int DistRemaining { get; set; }
        public int TimeRemaining { get; set; }
        public decimal MinReqFuel { get; set; }
        public decimal FuelFlowPerEng { get; set; }
        public int Temperature { get; set; }
        public int MORA { get; set; }
        public decimal Frequency { get; set; }
        public int WindComponent { get; set; }
        public int MinimumEnrouteAltitude { get; set; }
        public decimal MagneticHeading { get; set; }
        public decimal TrueHeading { get; set; }
        public int MagneticTrack { get; set; }
        public int TrueTrack { get; set; }
        public string HLAEntryExit { get; set; }
        public string FIR { get; set; }
        public string ClimbDescent { get; set; }
        public decimal LegFuel { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
