//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltAirport
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Icao { get; set; }
        public Nullable<int> Dist { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Fuel { get; set; }
        public Nullable<int> MAGCURS { get; set; }
        public string ATC { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<int> Rwyl { get; set; }
        public Nullable<int> Elevation { get; set; }
        public string Name { get; set; }
        public string Iata { get; set; }
        public string Category { get; set; }
        public Nullable<int> AirportHoursId { get; set; }
    
        public virtual AirportHour AirportHour { get; set; }
    }
}
