//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmPositionTakeoff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArmPositionTakeoff()
        {
            this.MassBalances = new HashSet<MassBalance>();
        }
    
        public int Id { get; set; }
        public Nullable<double> ForwardLimit { get; set; }
        public Nullable<double> ActualPosition { get; set; }
        public Nullable<double> AftLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassBalance> MassBalances { get; set; }
    }
}
