//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContingencySavingData
    {
        public int Id { get; set; }
        public Nullable<int> ContingencySavingAirportId { get; set; }
        public Nullable<int> ContingencySavingAlternateId { get; set; }
        public Nullable<int> ContingencySavingEnRouteAlternateAirportId { get; set; }
    
        public virtual AirportWeatherData AirportWeatherData { get; set; }
        public virtual AirportWeatherData AirportWeatherData1 { get; set; }
        public virtual AirportWeatherData AirportWeatherData2 { get; set; }
    }
}
