//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPTaf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPTaf()
        {
            this.Flights = new HashSet<Flight>();
        }
    
        public int Id { get; set; }
        public int FlightID { get; set; }
        public byte Type { get; set; }
        public string Text { get; set; }
        public string ICAO { get; set; }
        public System.DateTime ForecastTime { get; set; }
        public System.DateTime ForecastStartTime { get; set; }
        public System.DateTime ForecastEndTime { get; set; }
    
        public virtual Flight Flight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
