//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETOPSSuitableAirport
    {
        public int Id { get; set; }
        public string ICAO { get; set; }
        public Nullable<int> TAFId { get; set; }
        public Nullable<int> MetarId { get; set; }
        public Nullable<int> EtopsId { get; set; }
    
        public virtual Metar Metar { get; set; }
        public virtual Taf Taf { get; set; }
        public virtual EtopsInformation EtopsInformation { get; set; }
    }
}
