//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtopsAlternate
    {
        public int Id { get; set; }
        public int EtopsId { get; set; }
        public string ICAO { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public string AirportHoursText { get; set; }
    
        public virtual EtopsInformation EtopsInformation { get; set; }
    }
}
