//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtopsProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EtopsProfile()
        {
            this.EtopsFullETPs = new HashSet<EtopsFullETP>();
        }
    
        public int Id { get; set; }
        public int EtopsId { get; set; }
        public int ProfileIndex { get; set; }
        public string ProfileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtopsFullETP> EtopsFullETPs { get; set; }
        public virtual EtopsInformation EtopsInformation { get; set; }
    }
}
