//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIROverflightCost
    {
        public int Id { get; set; }
        public string FIR { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> OverflightCostId { get; set; }
    
        public virtual OverflightCost OverflightCost { get; set; }
    }
}
