//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightLevel
    {
        public int Id { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> WC { get; set; }
        public Nullable<double> TimeNCruise { get; set; }
        public Nullable<int> FuelNCruise { get; set; }
        public Nullable<double> TimeProfile2 { get; set; }
        public Nullable<int> FuelProfile2 { get; set; }
        public Nullable<double> TimeProfile3 { get; set; }
        public Nullable<int> FuelProfile3 { get; set; }
        public Nullable<int> FuelLower { get; set; }
        public Nullable<int> CostDiff { get; set; }
    }
}
