//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullEqualTimePoint
    {
        public int Id { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> Mass { get; set; }
        public Nullable<int> MassAtETP { get; set; }
        public Nullable<int> TimeDESTToETP { get; set; }
        public Nullable<int> DistanceDESTToETP { get; set; }
        public Nullable<int> TimeETPToAlternate { get; set; }
        public Nullable<int> ActualFuel { get; set; }
        public Nullable<int> MinimumRequiredFuel { get; set; }
        public Nullable<int> RemainingFuel { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
