//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load_Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Load_Cargo()
        {
            this.Load_CargoSection = new HashSet<Load_CargoSection>();
        }
    
        public int Id { get; set; }
        public int LoadId { get; set; }
        public Nullable<double> ActTotal { get; set; }
    
        public virtual Load Load { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Load_CargoSection> Load_CargoSection { get; set; }
    }
}
