//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class load_sheet_visit_history
    {
        public int id { get; set; }
        public int load_sheet_id { get; set; }
        public Nullable<int> crew_id { get; set; }
        public Nullable<System.DateTime> date_visit { get; set; }
        public Nullable<System.DateTime> date_sign { get; set; }
    
        public virtual load_sheet_raw load_sheet_raw { get; set; }
    }
}
