//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalTime()
        {
            this.Flights = new HashSet<Flight>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DepartureId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public Nullable<int> FlightID { get; set; }
    
        public virtual LocalTimeDeparture LocalTimeDeparture { get; set; }
        public virtual LocalTimeDestination LocalTimeDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
