//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassBalanceIndex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MassBalanceIndex()
        {
            this.MassBalances = new HashSet<MassBalance>();
        }
    
        public int Id { get; set; }
        public Nullable<double> DryOperatingIndex { get; set; }
        public Nullable<double> ZeroFuelForwardLimit { get; set; }
        public Nullable<double> ZeroFuelWeightIndex { get; set; }
        public Nullable<double> ZeroFuelAftLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassBalance> MassBalances { get; set; }
    }
}
