//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPA_aldrf
    {
        public int id { get; set; }
        public int FlightPlanId { get; set; }
        public int FL { get; set; }
        public string AVG_WIND { get; set; }
        public Nullable<int> DELTA_FUEL { get; set; }
        public Nullable<int> DELTA_T { get; set; }
        public Nullable<int> DELTA_SH { get; set; }
        public Nullable<int> M_SH { get; set; }
        public Nullable<int> ISA_DEV { get; set; }
        public bool IS_BASELINE { get; set; }
    
        public virtual OFPA_Main OFPA_Main { get; set; }
    }
}
