//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPA_pdptbl
    {
        public int id { get; set; }
        public int FlightPlanId { get; set; }
        public Nullable<short> FLL { get; set; }
        public string APT { get; set; }
        public string PDP { get; set; }
        public Nullable<decimal> ATI { get; set; }
        public string FRQ { get; set; }
        public string RWY { get; set; }
        public string PRT { get; set; }
        public Nullable<int> FUR { get; set; }
        public Nullable<int> FUQ { get; set; }
        public Nullable<int> FUD { get; set; }
        public string TIM { get; set; }
        public Nullable<int> DIS { get; set; }
    
        public virtual OFPA_Main OFPA_Main { get; set; }
    }
}
