//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPA_wdtmp
    {
        public int id { get; set; }
        public int FlightPlanId { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string WPT { get; set; }
        public int FL { get; set; }
        public Nullable<int> WDIR { get; set; }
        public Nullable<int> WSPD { get; set; }
        public Nullable<int> TMP_DEV { get; set; }
    
        public virtual OFPA_Main OFPA_Main { get; set; }
    }
}
