//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payload()
        {
            this.Loads = new HashSet<Load>();
        }
    
        public int Id { get; set; }
        public Nullable<double> MaxPayload { get; set; }
        public Nullable<double> Mzfm { get; set; }
        public Nullable<double> Mtom { get; set; }
        public Nullable<double> Mlm { get; set; }
        public Nullable<double> Mrmp { get; set; }
        public Nullable<double> MaxCargo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Load> Loads { get; set; }
    }
}
