//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanningEnRouteAlternateAirport
    {
        public int Id { get; set; }
        public string ICAO { get; set; }
        public Nullable<int> FlightId { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
