//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSPoint
    {
        public Nullable<int> FlightID { get; set; }
        public string PointSet { get; set; }
        public Nullable<int> ID { get; set; }
        public string IDENT { get; set; }
        public Nullable<int> FL { get; set; }
        public Nullable<int> Wind { get; set; }
        public Nullable<int> Vol { get; set; }
        public Nullable<int> ISA { get; set; }
        public Nullable<int> LegTime { get; set; }
        public Nullable<decimal> LegCourse { get; set; }
        public Nullable<int> LegDistance { get; set; }
        public Nullable<int> LegCAT { get; set; }
        public string LegName { get; set; }
        public string LegAWY { get; set; }
        public Nullable<decimal> FuelUsed { get; set; }
        public Nullable<int> FuelFlow { get; set; }
        public Nullable<decimal> LAT { get; set; }
        public Nullable<decimal> LON { get; set; }
        public Nullable<int> VARIATION { get; set; }
        public Nullable<int> ACCDIST { get; set; }
        public Nullable<int> ACCTIME { get; set; }
        public Nullable<decimal> MagCourse { get; set; }
        public Nullable<int> TrueAirSpeed { get; set; }
        public Nullable<int> GroundSpeed { get; set; }
        public Nullable<decimal> FuelRemaining { get; set; }
        public Nullable<int> DistRemaining { get; set; }
        public Nullable<int> TimeRemaining { get; set; }
        public Nullable<decimal> MinReqFuel { get; set; }
        public Nullable<decimal> FuelFlowPerEng { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<int> MORA { get; set; }
        public Nullable<decimal> Frequency { get; set; }
        public Nullable<int> WindComponent { get; set; }
        public Nullable<int> MinimumEnrouteAltitude { get; set; }
        public Nullable<decimal> MagneticHeading { get; set; }
        public Nullable<decimal> TrueHeading { get; set; }
        public Nullable<int> MagneticTrack { get; set; }
        public Nullable<int> TrueTrack { get; set; }
        public string HLAEntryExit { get; set; }
        public string FIR { get; set; }
        public string ClimbDescent { get; set; }
        public Nullable<decimal> LegFuel { get; set; }
        public int Id_Point { get; set; }
        public string PlanType { get; set; }
    }
}
