//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCFData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RCFData()
        {
            this.RCFRoutePoints = new HashSet<RCFRoutePoint>();
            this.RCFAltRoutePoints = new HashSet<RCFAltRoutePoint>();
            this.Flights = new HashSet<Flight>();
        }
    
        public int Id { get; set; }
        public string RCFAirport { get; set; }
        public string RCFAlternate { get; set; }
        public string DecisionPoint { get; set; }
        public string ATCRoute { get; set; }
        public Nullable<int> MinReqFuel { get; set; }
        public Nullable<int> TripFuel { get; set; }
        public Nullable<int> AlternateFuel { get; set; }
        public Nullable<int> ExtraFuel { get; set; }
        public Nullable<int> HoldingFuel { get; set; }
        public Nullable<int> ContFuel { get; set; }
        public string RCFERAAirport { get; set; }
        public Nullable<int> FlightID { get; set; }
        public string ContingencySavingAirportICAO { get; set; }
        public string ContingencySavingAlternateICAO { get; set; }
        public string ContingencySavingEnRouteAlternateAirportICAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCFRoutePoint> RCFRoutePoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCFAltRoutePoint> RCFAltRoutePoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
