//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SidAndStarProcedure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SidAndStarProcedure()
        {
            this.Flights = new HashSet<Flight>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SidId { get; set; }
        public Nullable<int> StarId { get; set; }
    
        public virtual SidStarInfoSid SidStarInfoSid { get; set; }
        public virtual SidStarInfoStar SidStarInfoStar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
