//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimplePaxSection
    {
        public int Id { get; set; }
        public string Row { get; set; }
        public Nullable<int> ActPax { get; set; }
        public Nullable<int> ActMass { get; set; }
        public Nullable<int> Male { get; set; }
        public Nullable<int> Female { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<int> Infant { get; set; }
        public string CustMass { get; set; }
    }
}
