//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_load_sheet_raw
    {
        public int id { get; set; }
        public string airline { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string content { get; set; }
        public string remark { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> signed_by_id { get; set; }
        public Nullable<System.DateTime> date_sign { get; set; }
        public string pic { get; set; }
        public string lic_no { get; set; }
        public string flight_no { get; set; }
        public Nullable<int> RefId { get; set; }
        public string Edition { get; set; }
        public string RowRefID { get; set; }
        public string MessageType { get; set; }
        public Nullable<int> history_id { get; set; }
        public string error_message { get; set; }
        public Nullable<System.DateTime> airline_server_request_date { get; set; }
        public string airline_server_response { get; set; }
        public string airline_server_error_message { get; set; }
        public Nullable<System.DateTime> notification_date { get; set; }
        public Nullable<System.DateTime> popup_date { get; set; }
        public Nullable<System.DateTime> pic_visited_date { get; set; }
        public Nullable<int> popup_count { get; set; }
        public Nullable<long> rank_last { get; set; }
    }
}
