//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_audit_plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms2_audit_plan()
        {
            this.cms2_audit = new HashSet<cms2_audit>();
            this.cms2_audit_team = new HashSet<cms2_audit_team>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int type_id { get; set; }
        public string objective { get; set; }
        public Nullable<int> lead_auditor { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> opening_meeting_start { get; set; }
        public Nullable<System.DateTime> opening_meeting_end { get; set; }
        public string opening_meeting_venue { get; set; }
        public Nullable<System.DateTime> closing_meeting_start { get; set; }
        public Nullable<System.DateTime> closing_meeting_end { get; set; }
        public string closing_meeting_venue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit> cms2_audit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_team> cms2_audit_team { get; set; }
        public virtual cms2_auditors cms2_auditors { get; set; }
    }
}
