//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCAO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaoMVTLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string MessageType { get; set; }
        public string Message { get; set; }
        public string Response { get; set; }
    }
}
