//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMnt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_mnt_aircraft_check
    {
        public int id { get; set; }
        public Nullable<int> item_no { get; set; }
        public string check { get; set; }
        public Nullable<int> remaining_hours { get; set; }
        public Nullable<int> remaining_minutes { get; set; }
        public Nullable<int> remaining_minutes_actual { get; set; }
        public Nullable<int> estimated_working_days { get; set; }
        public Nullable<int> aircraft_id { get; set; }
        public Nullable<System.DateTime> date_initial { get; set; }
        public string tasks { get; set; }
    }
}
