//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMnt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_mnt_engine
    {
        public int id { get; set; }
        public Nullable<int> engine_no { get; set; }
        public string cat { get; set; }
        public string model { get; set; }
        public string serial_no { get; set; }
        public Nullable<int> remaining_cycles { get; set; }
        public Nullable<int> remaining_cycles_actual { get; set; }
        public Nullable<int> remaining_minutes { get; set; }
        public Nullable<int> remaining_minutes_actual { get; set; }
        public Nullable<int> aircraft_id { get; set; }
        public Nullable<System.DateTime> date_initial { get; set; }
        public Nullable<int> flt_count { get; set; }
        public Nullable<int> total_flight_cycle { get; set; }
        public Nullable<int> total_flight_hour { get; set; }
    }
}
