//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMnt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vira_requestlog
    {
        public int Id { get; set; }
        public string paperNo { get; set; }
        public Nullable<int> paperId { get; set; }
        public Nullable<int> paperItemId { get; set; }
        public string paperType { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public string errorMessage { get; set; }
        public string requestPayload { get; set; }
        public string requestUrl { get; set; }
    }
}
