//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QACyber
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOccurrence { get; set; }
        public string JobTitle { get; set; }
        public string ContactInfo { get; set; }
        public Nullable<System.DateTime> DateIncident { get; set; }
        public Nullable<int> IncidentId { get; set; }
        public string IncidentDescription { get; set; }
        public Nullable<int> MethodId { get; set; }
        public string MethodDescription { get; set; }
        public Nullable<int> AccessId { get; set; }
        public string AccessDescription { get; set; }
        public string ImpactDescription { get; set; }
        public string BreachedDescription { get; set; }
        public string AttackDescriptipn { get; set; }
        public string Other { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<int> StatusEmployeeId { get; set; }
        public string Result { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string AccessMeasure { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string DelayReason { get; set; }
        public Nullable<int> Delay { get; set; }
        public string FormNo { get; set; }
    
        public virtual FlightInformation FlightInformation { get; set; }
        public virtual QAOption QAOption { get; set; }
        public virtual QAOption QAOption1 { get; set; }
        public virtual QAOption QAOption2 { get; set; }
    }
}
