//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAMaintenance
    {
        public int Id { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<System.DateTime> DateOccurrence { get; set; }
        public Nullable<int> ComponentSpecificationId { get; set; }
        public string ATLNo { get; set; }
        public string TaskNo { get; set; }
        public string Reference { get; set; }
        public Nullable<int> StationId { get; set; }
        public string EventDescription { get; set; }
        public string ActionTakenDescription { get; set; }
        public string Name { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string CAALicenceNo { get; set; }
        public string AuthorizationNo { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public Nullable<int> PartNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<int> StatusEmployeeId { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateHazard { get; set; }
        public string DelayReason { get; set; }
        public Nullable<int> Delay { get; set; }
    
        public virtual FlightInformation FlightInformation { get; set; }
        public virtual QAOption QAOption { get; set; }
        public virtual Airport Airport { get; set; }
    }
}
