//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QASecurity
    {
        public int Id { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<System.DateTime> DateReport { get; set; }
        public Nullable<System.DateTime> DateOccurrence { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public string ReasonDescription { get; set; }
        public string Camera { get; set; }
        public string CarryingBox { get; set; }
        public string HandRocket { get; set; }
        public string Comail { get; set; }
        public string Other { get; set; }
        public string EquipmentDescription { get; set; }
        public Nullable<bool> InjuryOccuring { get; set; }
        public string InjuryDescription { get; set; }
        public Nullable<bool> WorkBreak { get; set; }
        public Nullable<int> WorkBreakPeriod { get; set; }
        public string PreventiveActions { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<int> StatusEmployeeId { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string TelNumber { get; set; }
        public string DelayReason { get; set; }
        public Nullable<int> Delay { get; set; }
        public string FormNo { get; set; }
    
        public virtual FlightInformation FlightInformation { get; set; }
        public virtual QAOption QAOption { get; set; }
    }
}
