//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDMCptIpDaily
    {
        public Nullable<System.DateTime> Day { get; set; }
        public string P1Name { get; set; }
        public Nullable<int> P1Id { get; set; }
        public string IpName { get; set; }
        public Nullable<int> IpId { get; set; }
        public string P1Code { get; set; }
        public string IpCode { get; set; }
        public Nullable<int> FlightCount { get; set; }
        public Nullable<int> EventCount { get; set; }
        public Nullable<int> HighCount { get; set; }
        public Nullable<int> MediumCount { get; set; }
        public Nullable<int> LowCount { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
