//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDMCptAirportEventMonthly
    {
        public Nullable<int> Month { get; set; }
        public int Year { get; set; }
        public Nullable<int> FlightCount { get; set; }
        public Nullable<int> EventsCount { get; set; }
        public Nullable<int> AirportId { get; set; }
        public string IATA { get; set; }
        public Nullable<int> ArrivalAirportEventCount { get; set; }
        public Nullable<int> DepartureAirportEventCount { get; set; }
        public string p1Name { get; set; }
        public Nullable<int> P1Id { get; set; }
        public string IPName { get; set; }
        public Nullable<int> IPId { get; set; }
        public string P2Name { get; set; }
        public Nullable<int> P2Id { get; set; }
        public string PF { get; set; }
    }
}
