//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDMFoMonthly
    {
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public string P2Name { get; set; }
        public Nullable<int> P2Id { get; set; }
        public string P2Code { get; set; }
        public Nullable<int> FlightCount { get; set; }
        public Nullable<int> EventCount { get; set; }
        public Nullable<int> HighCount { get; set; }
        public Nullable<int> MediumCount { get; set; }
        public Nullable<int> LowCount { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<decimal> ScorePerEvent { get; set; }
        public Nullable<int> ScorePerFlight { get; set; }
        public Nullable<int> EventPerFlight { get; set; }
        public Nullable<int> HighScore { get; set; }
        public Nullable<int> MediumScore { get; set; }
        public Nullable<int> LowScore { get; set; }
    }
}
