//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDMPhaseDetailCrewByEvent
    {
        public int Id { get; set; }
        public string Phase { get; set; }
        public int FlightId { get; set; }
        public string FlightNumber { get; set; }
        public string FromICAO { get; set; }
        public string ToICAO { get; set; }
        public string FromIATA { get; set; }
        public string ToIATA { get; set; }
        public string RouteICAO { get; set; }
        public string RouteIATA { get; set; }
        public string Register { get; set; }
        public int RegisterID { get; set; }
        public string AircraftType { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public string Name { get; set; }
        public int CrewId { get; set; }
        public string JobGroup { get; set; }
        public Nullable<int> EventCount { get; set; }
        public int HighCount { get; set; }
        public int MediumCount { get; set; }
        public int LowCount { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> HighScore { get; set; }
        public Nullable<int> MediumScore { get; set; }
        public int LowScore { get; set; }
        public string Severity { get; set; }
        public string EventName { get; set; }
        public string Value { get; set; }
        public Nullable<double> Minor { get; set; }
        public Nullable<double> Major { get; set; }
        public Nullable<double> Critical { get; set; }
        public Nullable<System.DateTime> TDDatetime { get; set; }
        public string StateName { get; set; }
        public string Context { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> TODatetime { get; set; }
        public string Units { get; set; }
        public string ValueName { get; set; }
        public string Limit { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Validity { get; set; }
        public string MainParameter { get; set; }
    }
}
