//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDMTypeAnnually
    {
        public Nullable<int> Year { get; set; }
        public Nullable<int> FlightCount { get; set; }
        public Nullable<int> EventCount { get; set; }
        public string AircraftType { get; set; }
        public int AircraftTypeId { get; set; }
        public Nullable<int> HighCount { get; set; }
        public Nullable<int> MediumCount { get; set; }
        public Nullable<int> LowCount { get; set; }
    }
}
