//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CrewSecretCode> CrewSecretCodes { get; set; }
        public virtual DbSet<AppLeg> AppLegs { get; set; }
        public virtual DbSet<ViewFDM> ViewFDMs { get; set; }
        public virtual DbSet<FDMAirportMonthly> FDMAirportMonthlies { get; set; }
        public virtual DbSet<FDMAVG> FDMAVGs { get; set; }
        public virtual DbSet<FDMCptAirportEventMonthly> FDMCptAirportEventMonthlies { get; set; }
        public virtual DbSet<FDMCptAirportMonthly> FDMCptAirportMonthlies { get; set; }
        public virtual DbSet<FDMCptAll> FDMCptAlls { get; set; }
        public virtual DbSet<FDMCptAnnually> FDMCptAnnuallies { get; set; }
        public virtual DbSet<FDMCptEventDaily> FDMCptEventDailies { get; set; }
        public virtual DbSet<FDMCptEventMonthly> FDMCptEventMonthlies { get; set; }
        public virtual DbSet<FDMCptFoMonthly> FDMCptFoMonthlies { get; set; }
        public virtual DbSet<FDMCptIpMonthly> FDMCptIpMonthlies { get; set; }
        public virtual DbSet<FDMCptMonthly> FDMCptMonthlies { get; set; }
        public virtual DbSet<FDMDaily> FDMDailies { get; set; }
        public virtual DbSet<FDMEventDaily> FDMEventDailies { get; set; }
        public virtual DbSet<FDMEventMonthly> FDMEventMonthlies { get; set; }
        public virtual DbSet<FDMFoEventMonthly> FDMFoEventMonthlies { get; set; }
        public virtual DbSet<FDMMonthly> FDMMonthlies { get; set; }
        public virtual DbSet<FDMPhaseDetailByEvent> FDMPhaseDetailByEvents { get; set; }
        public virtual DbSet<FDMPhaseDetailByFlight> FDMPhaseDetailByFlights { get; set; }
        public virtual DbSet<FDMPhaseDetailCrewByEvent> FDMPhaseDetailCrewByEvents { get; set; }
        public virtual DbSet<FDMPhaseDetailDaily> FDMPhaseDetailDailies { get; set; }
        public virtual DbSet<FDMPhaseMonthly> FDMPhaseMonthlies { get; set; }
        public virtual DbSet<FDMPhaseMonthlyNoCrew> FDMPhaseMonthlyNoCrews { get; set; }
        public virtual DbSet<FDMRegCptDaily_> FDMRegCptDaily_ { get; set; }
        public virtual DbSet<FDMRegCptMonthly> FDMRegCptMonthlies { get; set; }
        public virtual DbSet<FDMRegDaily> FDMRegDailies { get; set; }
        public virtual DbSet<FDMRegEventMonthly> FDMRegEventMonthlies { get; set; }
        public virtual DbSet<FDMRegFoMonthly> FDMRegFoMonthlies { get; set; }
        public virtual DbSet<FDMRegMonthly> FDMRegMonthlies { get; set; }
        public virtual DbSet<FDMCptMonthlyTBL> FDMCptMonthlyTBLs { get; set; }
        public virtual DbSet<FDMEventParameter> FDMEventParameters { get; set; }
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<Ac_MSN> Ac_MSN { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<FlightInformation> FlightInformations { get; set; }
        public virtual DbSet<helper_fdm> helper_fdm { get; set; }
        public virtual DbSet<FDM> FDMs { get; set; }
        public virtual DbSet<view_fdm_flight_crew> view_fdm_flight_crew { get; set; }
        public virtual DbSet<view_fdm_processed> view_fdm_processed { get; set; }
        public virtual DbSet<fdm_crew> fdm_crew { get; set; }
        public virtual DbSet<fdm_processed> fdm_processed { get; set; }
    
        public virtual int FillFDMCptMonthlyTBL(Nullable<int> yearFrom, Nullable<int> monthFrom, Nullable<int> yearTo, Nullable<int> monthTo)
        {
            var yearFromParameter = yearFrom.HasValue ?
                new ObjectParameter("YearFrom", yearFrom) :
                new ObjectParameter("YearFrom", typeof(int));
    
            var monthFromParameter = monthFrom.HasValue ?
                new ObjectParameter("MonthFrom", monthFrom) :
                new ObjectParameter("MonthFrom", typeof(int));
    
            var yearToParameter = yearTo.HasValue ?
                new ObjectParameter("YearTo", yearTo) :
                new ObjectParameter("YearTo", typeof(int));
    
            var monthToParameter = monthTo.HasValue ?
                new ObjectParameter("MonthTo", monthTo) :
                new ObjectParameter("MonthTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FillFDMCptMonthlyTBL", yearFromParameter, monthFromParameter, yearToParameter, monthToParameter);
        }
    }
}
