//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pps_RoutePoint
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public string XmlID { get; set; }
        public string RoutePointType { get; set; }
        public string IDENT { get; set; }
        public Nullable<double> FL { get; set; }
        public Nullable<double> Wind { get; set; }
        public Nullable<double> Vol { get; set; }
        public Nullable<double> ISA { get; set; }
        public Nullable<double> LegTime { get; set; }
        public Nullable<double> LegCourse { get; set; }
        public Nullable<double> LegDistance { get; set; }
        public Nullable<double> LegCAT { get; set; }
        public string LegName { get; set; }
        public string LegAWY { get; set; }
        public Nullable<double> FuelUsed { get; set; }
        public Nullable<double> FuelFlow { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LON { get; set; }
        public Nullable<double> VARIATION { get; set; }
        public Nullable<double> ACCDIST { get; set; }
        public Nullable<double> ACCTIME { get; set; }
        public Nullable<double> MagCourse { get; set; }
        public Nullable<double> TrueAirSpeed { get; set; }
        public Nullable<double> GroundSpeed { get; set; }
        public Nullable<double> FuelRemaining { get; set; }
        public Nullable<double> DistRemaining { get; set; }
        public Nullable<double> TimeRemaining { get; set; }
        public Nullable<double> MinReqFuel { get; set; }
        public Nullable<double> FuelFlowPerEng { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> MORA { get; set; }
        public Nullable<double> Frequency { get; set; }
        public Nullable<double> WindComponent { get; set; }
        public Nullable<double> MinimumEnrouteAltitude { get; set; }
        public Nullable<double> Eco_OptSpeedFL { get; set; }
        public Nullable<double> Eco_SpeedGain { get; set; }
        public Nullable<double> Eco_OptEcoFL { get; set; }
        public Nullable<double> Eco_MoneyGain { get; set; }
        public Nullable<double> Eco_OptFuelFL { get; set; }
        public Nullable<double> Eco_FuelGain { get; set; }
        public Nullable<double> MagneticHeading { get; set; }
        public Nullable<double> TrueHeading { get; set; }
        public Nullable<double> MagneticTrack { get; set; }
        public Nullable<double> TrueTrack { get; set; }
        public string HLAEntryExit { get; set; }
        public string FIR { get; set; }
        public string ClimbDescent { get; set; }
        public Nullable<double> LegFuel { get; set; }
    
        public virtual pps_Flight pps_Flight { get; set; }
    }
}
