//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pps_Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pps_Flight()
        {
            this.pps_AirportWeatherData = new HashSet<pps_AirportWeatherData>();
            this.pps_AltAirport = new HashSet<pps_AltAirport>();
            this.pps_CorrectionTable = new HashSet<pps_CorrectionTable>();
            this.pps_Crew = new HashSet<pps_Crew>();
            this.pps_ExtraFuel = new HashSet<pps_ExtraFuel>();
            this.pps_FIROverflightCost = new HashSet<pps_FIROverflightCost>();
            this.pps_FlightLevel = new HashSet<pps_FlightLevel>();
            this.pps_PaxSection = new HashSet<pps_PaxSection>();
            this.pps_RoutePoint = new HashSet<pps_RoutePoint>();
            this.pps_String = new HashSet<pps_String>();
            this.pps_TAF = new HashSet<pps_TAF>();
            this.pps_Notam = new HashSet<pps_Notam>();
        }
    
        public int Id { get; set; }
        public string FlightLogID { get; set; }
        public string XmlID { get; set; }
        public string PPSName { get; set; }
        public string ACFTAIL { get; set; }
        public string DEP { get; set; }
        public string DEST { get; set; }
        public string ALT1 { get; set; }
        public string ALT2 { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<double> PAX { get; set; }
        public Nullable<double> FUEL { get; set; }
        public Nullable<double> LOAD { get; set; }
        public Nullable<double> ValidHrs { get; set; }
        public Nullable<double> MinFL { get; set; }
        public Nullable<double> MaxFL { get; set; }
        public string TOA { get; set; }
        public string FMDID { get; set; }
        public string DESTSTDALT { get; set; }
        public Nullable<double> FUELCOMP { get; set; }
        public string TIMECOMP { get; set; }
        public Nullable<double> FUELCONT { get; set; }
        public string TIMECONT { get; set; }
        public Nullable<double> PCTCONT { get; set; }
        public Nullable<double> FUELMIN { get; set; }
        public string TIMEMIN { get; set; }
        public Nullable<double> FUELTAXI { get; set; }
        public Nullable<double> TIMETAXI { get; set; }
        public Nullable<double> FUELEXTRA { get; set; }
        public string TIMEEXTRA { get; set; }
        public Nullable<double> FUELLDG { get; set; }
        public string TIMELDG { get; set; }
        public Nullable<double> ZFM { get; set; }
        public Nullable<double> GCD { get; set; }
        public Nullable<double> ESAD { get; set; }
        public string GL { get; set; }
        public Nullable<double> FUELBIAS { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<double> SCHBLOCKTIME { get; set; }
        public string DISP { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> LatestFlightPlanDate { get; set; }
        public Nullable<System.DateTime> LatestDocumentUploadDate { get; set; }
        public Nullable<double> FUELMINTO { get; set; }
        public Nullable<double> TIMEMINTO { get; set; }
        public Nullable<double> ARAMP { get; set; }
        public Nullable<double> TIMEACT { get; set; }
        public Nullable<double> FUELACT { get; set; }
        public string DestERA { get; set; }
        public Nullable<double> TrafficLoad { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<double> WindComponent { get; set; }
        public string CustomerDataPPS { get; set; }
        public string CustomerDataScheduled { get; set; }
        public Nullable<double> Fl { get; set; }
        public Nullable<double> RouteDistNM { get; set; }
        public string RouteName { get; set; }
        public string RouteRemark { get; set; }
        public Nullable<double> EmptyWeight { get; set; }
        public Nullable<double> TotalDistance { get; set; }
        public Nullable<double> AltDist { get; set; }
        public Nullable<double> DestTime { get; set; }
        public Nullable<double> AltTime { get; set; }
        public Nullable<double> AltFuel { get; set; }
        public Nullable<double> HoldTime { get; set; }
        public Nullable<double> ReserveTime { get; set; }
        public Nullable<double> Cargo { get; set; }
        public Nullable<double> ActTOW { get; set; }
        public Nullable<double> TripFuel { get; set; }
        public Nullable<double> HoldFuel { get; set; }
        public Nullable<double> Elw { get; set; }
        public string FuelPolicy { get; set; }
        public Nullable<double> Alt2Time { get; set; }
        public Nullable<double> Alt2Fuel { get; set; }
        public Nullable<double> MaxTOM { get; set; }
        public Nullable<double> MaxLM { get; set; }
        public Nullable<double> MaxZFM { get; set; }
        public Nullable<System.DateTime> WeatherObsTime { get; set; }
        public Nullable<System.DateTime> WeatherPlanTime { get; set; }
        public string MFCI { get; set; }
        public string CruiseProfile { get; set; }
        public Nullable<double> TempTopOfClimb { get; set; }
        public string Climb { get; set; }
        public string Descend { get; set; }
        public string FuelPL { get; set; }
        public string DescendWind { get; set; }
        public string ClimbProfile { get; set; }
        public string DescendProfile { get; set; }
        public string HoldProfile { get; set; }
        public string StepClimbProfile { get; set; }
        public string FuelContDef { get; set; }
        public string FuelAltDef { get; set; }
        public string AmexsyStatus { get; set; }
        public Nullable<double> AvgTrack { get; set; }
        public string DEPMetar { get; set; }
        public string DESTMetar { get; set; }
        public string ALT1Metar { get; set; }
        public string ALT2Metar { get; set; }
        public string EnrouteAlternates { get; set; }
        public string StdAlternates { get; set; }
        public string TOALT { get; set; }
        public string RouteStrings_ToDest { get; set; }
        public string RouteStrings_ToAlt1 { get; set; }
        public string RouteStrings_ToAlt2 { get; set; }
        public string RouteStrings_TOAlt { get; set; }
        public string DEPIATA { get; set; }
        public string DESTIATA { get; set; }
        public Nullable<double> FinalReserveMinutes { get; set; }
        public Nullable<double> FinalReserveFuel { get; set; }
        public Nullable<double> AddFuelMinutes { get; set; }
        public Nullable<double> AddFuel { get; set; }
        public string FlightSummary { get; set; }
        public string PassThroughValues { get; set; }
        public Nullable<double> EtopsInformation_RuleTimeUsed { get; set; }
        public Nullable<double> EtopsInformation_IcingPercentage { get; set; }
        public Nullable<double> FuelINCRBurn { get; set; }
        public string ExternalFlightId { get; set; }
        public string GUFI { get; set; }
        public string SidProcedures_Name { get; set; }
        public string SidProcedures_Info { get; set; }
        public string StarProcedures_Name { get; set; }
        public string StarProcedures_Info { get; set; }
        public Nullable<double> FMRI { get; set; }
        public Nullable<double> Load_Fuel_ActTotal { get; set; }
        public Nullable<double> Load_Fuel_Section_ActMass { get; set; }
        public string Load_Fuel_Section_ID { get; set; }
        public Nullable<double> Load_Cargo_ActTotal { get; set; }
        public Nullable<double> Load_Cargo_Section_ActMass { get; set; }
        public string Load_Cargo_Section_ID { get; set; }
        public Nullable<double> Load_Pax_Total { get; set; }
        public Nullable<double> Load_Pax_Data_MaxPax { get; set; }
        public Nullable<double> Load_Pax_Data_ActPax { get; set; }
        public Nullable<double> Load_Pax_Data_ActMass { get; set; }
        public Nullable<double> Load_Pax_Data_PaxAmount { get; set; }
        public Nullable<double> Load_Pax_Data_Male { get; set; }
        public Nullable<double> Load_Pax_Data_Female { get; set; }
        public Nullable<double> Load_Pax_Data_Children { get; set; }
        public Nullable<double> Load_Pax_Data_Infant { get; set; }
        public string Load_Pax_Data_CustMass { get; set; }
        public Nullable<double> Load_MassBalance_Takeoff_ForwardLimit { get; set; }
        public Nullable<double> Load_MassBalance_Takeoff_ActualPosition { get; set; }
        public Nullable<double> Load_MassBalance_Takeoff_AftLimit { get; set; }
        public Nullable<double> Load_MassBalance_Landing_ForwardLimit { get; set; }
        public Nullable<double> Load_MassBalance_Landing_ActualPosition { get; set; }
        public Nullable<double> Load_MassBalance_Landing_AftLimit { get; set; }
        public Nullable<double> Load_MassBalance_ZeroFuel_ForwardLimit { get; set; }
        public Nullable<double> Load_MassBalance_ZeroFuel_ActualPosition { get; set; }
        public Nullable<double> Load_MassBalance_ZeroFuel_AftLimit { get; set; }
        public Nullable<double> Load_MassBalance_Index_DryOperatingIndex { get; set; }
        public Nullable<double> Load_MassBalance_Index_ZeroFuelForwardLimit { get; set; }
        public Nullable<double> Load_MassBalance_Index_ZeroFuelWeightIndex { get; set; }
        public Nullable<double> Load_MassBalance_Index_ZeroFuelAftLimit { get; set; }
        public Nullable<double> Load_Payload_MaxPayload { get; set; }
        public Nullable<double> Load_Payload_Mzfm { get; set; }
        public Nullable<double> Load_Payload_Mtom { get; set; }
        public Nullable<double> Load_Payload_Mlm { get; set; }
        public Nullable<double> Load_Payload_Mrmp { get; set; }
        public Nullable<double> Load_Payload_MaxCargo { get; set; }
        public Nullable<double> Load_DryOperating_BasicEmptyArm { get; set; }
        public Nullable<double> Load_DryOperating_BasicEmptyWeight { get; set; }
        public Nullable<double> Load_DryOperating_DryOperatingMassArm { get; set; }
        public Nullable<double> Load_DryOperating_DryOperatingWeight { get; set; }
        public string AircraftConfiguration_Name { get; set; }
        public Nullable<bool> IsRecalc { get; set; }
        public Nullable<double> MaxRampWeight { get; set; }
        public string UnderloadFactor { get; set; }
        public Nullable<double> AvgISA { get; set; }
        public string HWCorrection20KtsTime { get; set; }
        public Nullable<double> HWCorrection20KtsFuel { get; set; }
        public Nullable<double> Correction1TON { get; set; }
        public Nullable<double> Correction2TON { get; set; }
        public string RcfHeader { get; set; }
        public Nullable<bool> ALT2AsInfoOnly { get; set; }
        public string PpsApplicationVersion { get; set; }
        public string PpsExeVersion { get; set; }
        public string CustomReferences_RefID { get; set; }
        public string CustomReferences_MilID { get; set; }
        public string CFMUStatus { get; set; }
        public Nullable<double> StructuralTOM { get; set; }
        public Nullable<double> FW1 { get; set; }
        public Nullable<double> FW2 { get; set; }
        public Nullable<double> FW3 { get; set; }
        public Nullable<double> FW4 { get; set; }
        public Nullable<double> FW5 { get; set; }
        public Nullable<double> FW6 { get; set; }
        public Nullable<double> FW7 { get; set; }
        public Nullable<double> FW8 { get; set; }
        public Nullable<double> FW9 { get; set; }
        public Nullable<double> TOTALPAXWEIGHT { get; set; }
        public Nullable<double> Alt2Dist { get; set; }
        public string FMSIdent { get; set; }
        public Nullable<double> AircraftFuelBias { get; set; }
        public Nullable<double> MelFuelBias { get; set; }
        public Nullable<System.DateTime> LocalTime_Departure_STD { get; set; }
        public Nullable<System.DateTime> LocalTime_Departure_ETD { get; set; }
        public Nullable<System.DateTime> LocalTime_Departure_Sunrise { get; set; }
        public Nullable<System.DateTime> LocalTime_Departure_Sunset { get; set; }
        public Nullable<System.DateTime> LocalTime_Destination_STA { get; set; }
        public Nullable<System.DateTime> LocalTime_Destination_ETA { get; set; }
        public Nullable<System.DateTime> LocalTime_Destination_Sunrise { get; set; }
        public Nullable<System.DateTime> LocalTime_Destination_Sunset { get; set; }
        public string OverflightCost_Currency { get; set; }
        public Nullable<double> OverflightCost_TotalOverflightCost { get; set; }
        public Nullable<double> OverflightCost_TotalTerminalCost { get; set; }
        public Nullable<double> Holding_Fuel { get; set; }
        public Nullable<double> Holding_Minutes { get; set; }
        public string Holding_Profile { get; set; }
        public string Holding_Specification { get; set; }
        public string Holding_FuelFlowType { get; set; }
        public string ATCData_ATCID { get; set; }
        public string ATCData_ATCTOA { get; set; }
        public string ATCData_ATCRule { get; set; }
        public string ATCData_ATCType { get; set; }
        public string ATCData_ATCNum { get; set; }
        public string ATCData_ATCWake { get; set; }
        public string ATCData_ATCEqui { get; set; }
        public string ATCData_ATCSSR { get; set; }
        public string ATCData_ATCDep { get; set; }
        public string ATCData_ATCTime { get; set; }
        public string ATCData_ATCSpeed { get; set; }
        public string ATCData_ATCFL { get; set; }
        public string ATCData_ATCRoute { get; set; }
        public string ATCData_ATCDest { get; set; }
        public string ATCData_ATCEET { get; set; }
        public string ATCData_ATCAlt1 { get; set; }
        public string ATCData_ATCAlt2 { get; set; }
        public string ATCData_ATCInfo { get; set; }
        public string ATCData_ATCEndu { get; set; }
        public string ATCData_ATCPers { get; set; }
        public string ATCData_ATCRadi { get; set; }
        public string ATCData_ATCSurv { get; set; }
        public string ATCData_ATCJack { get; set; }
        public string ATCData_ATCDing { get; set; }
        public string ATCData_ATCCap { get; set; }
        public string ATCData_ATCCover { get; set; }
        public string ATCData_ATCColo { get; set; }
        public string ATCData_ATCAcco { get; set; }
        public string ATCData_ATCRem { get; set; }
        public string ATCData_ATCPIC { get; set; }
        public string ATCData_ATCCtot { get; set; }
        public Nullable<bool> Responce_Succeed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_AirportWeatherData> pps_AirportWeatherData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_AltAirport> pps_AltAirport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_CorrectionTable> pps_CorrectionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_Crew> pps_Crew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_ExtraFuel> pps_ExtraFuel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_FIROverflightCost> pps_FIROverflightCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_FlightLevel> pps_FlightLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_PaxSection> pps_PaxSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_RoutePoint> pps_RoutePoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_String> pps_String { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_TAF> pps_TAF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pps_Notam> pps_Notam { get; set; }
    }
}
