//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pps_PaxSection
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public string PaxSectionType { get; set; }
        public string Row { get; set; }
        public Nullable<double> ActPax { get; set; }
        public Nullable<double> ActMass { get; set; }
        public Nullable<double> Male { get; set; }
        public Nullable<double> Female { get; set; }
        public Nullable<double> Children { get; set; }
        public Nullable<double> Infant { get; set; }
        public string CutsMass { get; set; }
    
        public virtual pps_Flight pps_Flight { get; set; }
    }
}
