//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pps_AirportWeatherData
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public string ICAO { get; set; }
        public string Taf_Type { get; set; }
        public string Taf_Text { get; set; }
        public string Taf_ICAO { get; set; }
        public Nullable<System.DateTime> Taf_ForecastTime { get; set; }
        public Nullable<System.DateTime> Taf_ForecastStartTime { get; set; }
        public Nullable<System.DateTime> Taf_ForecastEndTime { get; set; }
        public string Metar_Text { get; set; }
        public string Metar_ICAO { get; set; }
        public Nullable<System.DateTime> Metar_ObservationTime { get; set; }
        public string Metar_ObservationType { get; set; }
    
        public virtual pps_Flight pps_Flight { get; set; }
    }
}
