//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pps_CorrectionTable
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public string CtID { get; set; }
        public Nullable<double> Flightlevel { get; set; }
        public Nullable<double> WindCorrection { get; set; }
        public Nullable<double> TimeInMinutesForCruiseProfile { get; set; }
        public Nullable<double> TimeInHoursMinutesForCruiseProfile { get; set; }
        public string TimeInHoursMinutesForAltCruiseProfile { get; set; }
        public string TimeInMinutesForAltCruiseProfile { get; set; }
        public Nullable<double> TimeInMinutesForXProfile { get; set; }
        public string TimeInHoursMinutesForXProfile { get; set; }
        public Nullable<double> FuelForSelectedProfile { get; set; }
        public Nullable<double> FuelForSecondProfile { get; set; }
        public Nullable<double> FuelForXProfile { get; set; }
        public Nullable<double> DifferentialCost { get; set; }
        public Nullable<double> TotalFuelIncreaseWith10ktWind { get; set; }
    
        public virtual pps_Flight pps_Flight { get; set; }
    }
}
