//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPSEntities : DbContext
    {
        public PPSEntities()
            : base("name=PPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pps_AirportWeatherData> pps_AirportWeatherData { get; set; }
        public virtual DbSet<pps_AltAirport> pps_AltAirport { get; set; }
        public virtual DbSet<pps_CorrectionTable> pps_CorrectionTable { get; set; }
        public virtual DbSet<pps_Crew> pps_Crew { get; set; }
        public virtual DbSet<pps_ExtraFuel> pps_ExtraFuel { get; set; }
        public virtual DbSet<pps_FIROverflightCost> pps_FIROverflightCost { get; set; }
        public virtual DbSet<pps_Flight> pps_Flight { get; set; }
        public virtual DbSet<pps_FlightLevel> pps_FlightLevel { get; set; }
        public virtual DbSet<pps_NotamPart> pps_NotamPart { get; set; }
        public virtual DbSet<pps_PaxSection> pps_PaxSection { get; set; }
        public virtual DbSet<pps_RoutePoint> pps_RoutePoint { get; set; }
        public virtual DbSet<pps_String> pps_String { get; set; }
        public virtual DbSet<pps_TAF> pps_TAF { get; set; }
        public virtual DbSet<pps_Notam> pps_Notam { get; set; }
    }
}
