//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAHazard
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TelNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> HazardDate { get; set; }
        public string AffectedArea { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string HazardDescription { get; set; }
        public string RecommendedAction { get; set; }
        public Nullable<int> EmploeeId { get; set; }
    }
}
