//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_fdm_flight_crew
    {
        public int id { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public string Register { get; set; }
        public string ac_type2 { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string Name { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string Position { get; set; }
        public int dep_id { get; set; }
        public string dep_iata { get; set; }
        public string dep_icao { get; set; }
        public int arr_id { get; set; }
        public string arr_iata { get; set; }
        public string arr_icao { get; set; }
    }
}
