//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQAMOR
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public Nullable<System.DateTime> OccurrenceDateTime { get; set; }
        public string AircraftType { get; set; }
        public string Register { get; set; }
        public Nullable<int> ComponentSpecificationId { get; set; }
        public string ComponentSpecification { get; set; }
        public string FlightRoute { get; set; }
        public string FlightNumber { get; set; }
        public string ATLNo { get; set; }
        public string TaskNo { get; set; }
        public string Reference { get; set; }
        public Nullable<int> StationId { get; set; }
        public string Station { get; set; }
        public string EventDescription { get; set; }
        public string ActionTakenDescription { get; set; }
        public Nullable<int> EmploeeId { get; set; }
        public string Name { get; set; }
        public string CAALicenceNo { get; set; }
        public string AuthorizationNo { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public Nullable<int> PartNumber { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
    }
}
