//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFDM
    {
        public Nullable<int> ToAirport { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public string ToAirportIATA { get; set; }
        public string FromAirportIATA { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Register { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> P1Id { get; set; }
        public string P1Code { get; set; }
        public Nullable<int> P2Id { get; set; }
        public string P2Code { get; set; }
        public Nullable<int> IPId { get; set; }
        public string IPCode { get; set; }
        public string IPName { get; set; }
        public string P1Name { get; set; }
        public string P2Name { get; set; }
        public Nullable<System.DateTime> BlockOff { get; set; }
        public Nullable<System.DateTime> BlockOn { get; set; }
        public Nullable<System.DateTime> TakeOff { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public string PF { get; set; }
        public string FlightNumber { get; set; }
        public string Context { get; set; }
        public Nullable<double> Critical { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string EventName { get; set; }
        public Nullable<int> FlightId { get; set; }
        public int Id { get; set; }
        public string Limit { get; set; }
        public Nullable<double> Major { get; set; }
        public Nullable<double> Minor { get; set; }
        public string PFLR { get; set; }
        public string Severity { get; set; }
        public string Phase { get; set; }
        public string StateName { get; set; }
        public Nullable<System.DateTime> TDDatetime { get; set; }
        public Nullable<System.DateTime> TODatetime { get; set; }
        public string Type { get; set; }
        public string Units { get; set; }
        public string Value { get; set; }
        public string ValueName { get; set; }
        public Nullable<bool> Removed { get; set; }
        public string RemovedBy { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<int> Validity { get; set; }
        public Nullable<bool> Confirmation { get; set; }
        public string ValidationPerson { get; set; }
        public string ConfirmationPerson { get; set; }
        public Nullable<int> ResponsibleId { get; set; }
        public string Responsible { get; set; }
        public string Status { get; set; }
        public string ValidityStatus { get; set; }
    }
}
