//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_pax_flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crm_pax_flight()
        {
            this.crm_crew_score = new HashSet<crm_crew_score>();
            this.crm_question_result = new HashSet<crm_question_result>();
        }
    
        public int id { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> passenger_id { get; set; }
        public Nullable<System.DateTime> date_send { get; set; }
        public string ref_id { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> date_result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_crew_score> crm_crew_score { get; set; }
        public virtual crm_pax crm_pax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_question_result> crm_question_result { get; set; }
    }
}
