//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_pax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crm_pax()
        {
            this.crm_pax_flight = new HashSet<crm_pax_flight>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string nid { get; set; }
        public string date_birth { get; set; }
        public string ticket_no { get; set; }
        public string remark { get; set; }
        public string first_name2 { get; set; }
        public string last_name2 { get; set; }
        public string passport_no { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> sex_id { get; set; }
        public string mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crm_pax_flight> crm_pax_flight { get; set; }
    }
}
