//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_crew_score
    {
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> crew_id { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string PFirstName { get; set; }
        public string PLastName { get; set; }
        public string PName { get; set; }
        public string NID { get; set; }
        public int GroupOrder { get; set; }
        public string JobGroup { get; set; }
        public Nullable<int> flight_pax_id { get; set; }
        public Nullable<int> score { get; set; }
    }
}
