//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class airline_route
    {
        public int id { get; set; }
        public string route { get; set; }
        public string remark { get; set; }
        public string ac_type { get; set; }
    }
}
