//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppa_Entities : DbContext
    {
        public ppa_Entities()
            : base("name=ppa_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ViewFinMonthlyRoute> ViewFinMonthlyRoutes { get; set; }
        public virtual DbSet<ViewFlightDelay> ViewFlightDelays { get; set; }
        public virtual DbSet<RptNoFDP> RptNoFDPs { get; set; }
        public virtual DbSet<ViewCrewFlightApp> ViewCrewFlightApps { get; set; }
        public virtual DbSet<RptNoFDPMonthlyPersian> RptNoFDPMonthlyPersians { get; set; }
        public virtual DbSet<airline_route> airline_route { get; set; }
        public virtual DbSet<view_fdp_fixtime> view_fdp_fixtime { get; set; }
        public virtual DbSet<rpt_pax_total> rpt_pax_total { get; set; }
        public virtual DbSet<RptFDP2> RptFDP2 { get; set; }
        public virtual DbSet<RptFDPReg> RptFDPRegs { get; set; }
        public virtual DbSet<RptFlightRVSM> RptFlightRVSMs { get; set; }
        public virtual DbSet<RptFuelOFP> RptFuelOFPs { get; set; }
        public virtual DbSet<RptRefuse> RptRefuses { get; set; }
        public virtual DbSet<summary_flight_pax> summary_flight_pax { get; set; }
        public virtual DbSet<ViewCourseFDP> ViewCourseFDPs { get; set; }
        public virtual DbSet<ViewDelayedFlight> ViewDelayedFlights { get; set; }
        public virtual DbSet<ViewFlightDaily> ViewFlightDailies { get; set; }
        public virtual DbSet<ViewFlightPax> ViewFlightPaxes { get; set; }
        public virtual DbSet<ViewFormB> ViewFormBs { get; set; }
        public virtual DbSet<ViewFormC> ViewFormCs { get; set; }
        public virtual DbSet<FDP> FDPs { get; set; }
        public virtual DbSet<XFlightCrew> XFlightCrews { get; set; }
        public virtual DbSet<Ac_MSN> Ac_MSN { get; set; }
        public virtual DbSet<RptFDPItem> RptFDPItems { get; set; }
        public virtual DbSet<ViewFlightCockpit> ViewFlightCockpits { get; set; }
        public virtual DbSet<ViewLegCrew> ViewLegCrews { get; set; }
        public virtual DbSet<ViewRegHistory> ViewRegHistories { get; set; }
        public virtual DbSet<ViewRegHistoryYearly> ViewRegHistoryYearlies { get; set; }
        public virtual DbSet<RptReposition> RptRepositions { get; set; }
        public virtual DbSet<view_stby> view_stby { get; set; }
        public virtual DbSet<view_layover> view_layover { get; set; }
        public virtual DbSet<ViewCrew> ViewCrews { get; set; }
        public virtual DbSet<rpt_crew_route> rpt_crew_route { get; set; }
        public virtual DbSet<rpt_citypair_daily> rpt_citypair_daily { get; set; }
        public virtual DbSet<helper_layover_ranked_new> helper_layover_ranked_new { get; set; }
        public virtual DbSet<helper_layover_ranked_new_prev> helper_layover_ranked_new_prev { get; set; }
    }
}
