//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_pax_total
    {
        public string Route { get; set; }
        public Nullable<int> Flights { get; set; }
        public int TotalPax { get; set; }
    }
}
