//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_citypair_daily
    {
        public Nullable<System.DateTime> date_local { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> std { get; set; }
        public Nullable<System.DateTime> sta { get; set; }
        public Nullable<System.DateTime> takeoff { get; set; }
        public Nullable<System.DateTime> landing { get; set; }
        public Nullable<System.DateTime> onblock { get; set; }
        public Nullable<System.DateTime> offblock { get; set; }
        public int pax_adults { get; set; }
        public int pax_children { get; set; }
        public int pax_infants { get; set; }
        public Nullable<int> pax_total { get; set; }
        public string dep { get; set; }
        public string dep_icao { get; set; }
        public string arr { get; set; }
        public string arr_icao { get; set; }
        public Nullable<int> dep_id { get; set; }
        public Nullable<int> arr_id { get; set; }
        public string route { get; set; }
        public string route_icao { get; set; }
    }
}
