//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptFuelOFP
    {
        public int ID { get; set; }
        public int OFPId { get; set; }
        public Nullable<int> OFPFuel { get; set; }
        public Nullable<int> ReqFuel { get; set; }
        public string Due { get; set; }
        public Nullable<int> DiffTotalFuel { get; set; }
        public Nullable<double> DiffPerTotalFuel { get; set; }
        public Nullable<int> TakeOffFuel { get; set; }
        public Nullable<int> OnBlockFuel { get; set; }
        public Nullable<int> Taxi { get; set; }
        public Nullable<int> OFPTaxi { get; set; }
        public Nullable<int> DiffTaxi { get; set; }
        public Nullable<double> DiffPerTaxi { get; set; }
        public Nullable<int> TripFuel { get; set; }
        public Nullable<int> OFPTripFuel { get; set; }
        public Nullable<int> DiffTripFuel { get; set; }
        public Nullable<double> DiffPerTripFuel { get; set; }
        public Nullable<double> FuelRate { get; set; }
        public string OFPTripTimeStr { get; set; }
        public Nullable<int> OFPTripTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<System.DateTime> BlockOn { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> TakeOff { get; set; }
        public Nullable<System.DateTime> BlockOff { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public string AircraftType { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string Register { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<int> ScheduledFlightTime { get; set; }
        public Nullable<int> PaxInfant { get; set; }
        public Nullable<int> PaxAdult { get; set; }
        public Nullable<int> PaxTotal { get; set; }
        public Nullable<int> PaxRevenued { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public Nullable<int> CargoCount { get; set; }
        public Nullable<int> BaggageCount { get; set; }
        public string IPName { get; set; }
        public Nullable<int> IPId { get; set; }
        public string P1Name { get; set; }
        public Nullable<int> P1Id { get; set; }
        public string P2Name { get; set; }
        public Nullable<int> P2Id { get; set; }
        public string PIC { get; set; }
        public string SIC { get; set; }
        public string JLSignedBy { get; set; }
        public string PF { get; set; }
        public Nullable<int> PFLR { get; set; }
        public Nullable<int> PaxChild { get; set; }
    }
}
