//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptFDP2
    {
        public int FDPId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ScheduleName { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STDDayUTC { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public int EarlyDeparture { get; set; }
        public int LateArrival { get; set; }
        public Nullable<int> WOCLTO { get; set; }
        public Nullable<int> WOCLLND { get; set; }
        public Nullable<int> WOCLDuration { get; set; }
        public Nullable<int> XAirportTO { get; set; }
        public Nullable<int> XAirportLND { get; set; }
        public Nullable<int> HolidayDeparture { get; set; }
        public string Flights { get; set; }
        public string Route { get; set; }
        public Nullable<int> LegsCnt { get; set; }
        public Nullable<int> Legs { get; set; }
        public Nullable<int> Canceled { get; set; }
        public Nullable<int> CanceledFixTime { get; set; }
        public Nullable<int> Positioning { get; set; }
        public Nullable<int> PositioningFixTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> FixedFlightTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> ScheduledTime { get; set; }
        public int Leg1 { get; set; }
        public int Leg2 { get; set; }
        public int Leg3 { get; set; }
        public int Leg4 { get; set; }
        public int Leg5 { get; set; }
        public int Leg6 { get; set; }
        public int Leg7 { get; set; }
        public int Leg8 { get; set; }
        public string DayName { get; set; }
        public Nullable<int> Year { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> Month { get; set; }
    }
}
