//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCourseFDP
    {
        public int FDPId { get; set; }
        public int EmployeeId { get; set; }
        public int CourseId { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseType { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Instructor { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string TrainingDirector { get; set; }
        public string Title { get; set; }
        public bool Recurrent { get; set; }
        public string No { get; set; }
        public string Organization { get; set; }
        public string HoldingType { get; set; }
        public Nullable<System.DateTime> SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
    }
}
