//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiXLS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPB_Alternate1NavLog
    {
        public int Id { get; set; }
        public string WayPoint { get; set; }
        public string FlightLevel { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Frequency { get; set; }
        public string Airway { get; set; }
        public string MEA { get; set; }
        public string MORA { get; set; }
        public Nullable<double> ZoneDistance { get; set; }
        public Nullable<double> CumulativeDistance { get; set; }
        public string Wind { get; set; }
        public string MagneticTrack { get; set; }
        public string Temperature { get; set; }
        public string ZoneTime { get; set; }
        public string CumulativeTime { get; set; }
        public Nullable<double> FuelRemained { get; set; }
        public Nullable<double> FuelUsed { get; set; }
        public Nullable<double> MachNo { get; set; }
        public Nullable<double> TrueAirSpeed { get; set; }
        public Nullable<double> GroundSpeed { get; set; }
        public Nullable<int> RootId { get; set; }
    
        public virtual OFPB_Root OFPB_Root { get; set; }
    }
}
