//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiXLS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPB_WindTemperatureCruise
    {
        public int Id { get; set; }
        public string FlightLevel { get; set; }
        public string Wind { get; set; }
        public string Temperature { get; set; }
        public Nullable<int> RootId { get; set; }
    
        public virtual OFPB_Root OFPB_Root { get; set; }
    }
}
