//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMSG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppa_vareshEntities : DbContext
    {
        public ppa_vareshEntities()
            : base("name=ppa_vareshEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MVT> MVTs { get; set; }
        public virtual DbSet<MVTAPI> MVTAPIs { get; set; }
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<ViewFlightDelayCode> ViewFlightDelayCodes { get; set; }
        public virtual DbSet<NiraHistory> NiraHistories { get; set; }
        public virtual DbSet<ViewNotificationTrn> ViewNotificationTrns { get; set; }
        public virtual DbSet<ViewNotificationTrnCount> ViewNotificationTrnCounts { get; set; }
        public virtual DbSet<ViewCertificateHistory> ViewCertificateHistories { get; set; }
        public virtual DbSet<NotificationTrn> NotificationTrns { get; set; }
        public virtual DbSet<BulkMsg> BulkMsgs { get; set; }
        public virtual DbSet<BulkMsgUsername> BulkMsgUsernames { get; set; }
        public virtual DbSet<ViewNira> ViewNiras { get; set; }
        public virtual DbSet<ViewNiraFlight> ViewNiraFlights { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<ManagerGroup> ManagerGroups { get; set; }
        public virtual DbSet<ViewProfile> ViewProfiles { get; set; }
    }
}
