//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMSG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTrn
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> CertificateTypeId { get; set; }
        public string CertificateType { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Ref { get; set; }
        public string SMSStatus { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public string Text { get; set; }
        public string Type { get; set; }
        public Nullable<int> Remain { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    }
}
