//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPlanning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelperFlightKey
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public string FlightNumber { get; set; }
        public string KeyUtc { get; set; }
    }
}
